### ISSUE TITLE
Logo suggestion

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#1]
## Why this issue?

With creating issues and uploading media, you can reference the url in the `readme.md` and therefore eg. add logos/screenshots to the frontpage of the project.

More important I want an open discussion about the "logo" for the project (eg. to use it in a splash screen of an editor or so).
## Current Output

I presented the idea of this logo some weeks ago to Brucey. I now remade the whole thing as pure vectors.

![bmx_ng_export2](https://cloud.githubusercontent.com/assets/2625226/6284436/3102414c-b8f0-11e4-96d6-ae25f27ac233.png)

![bmx_ng_export1a](https://cloud.githubusercontent.com/assets/2625226/6284567/93cdbf1c-b8f1-11e4-83e1-3d86440db16c.png)

Currently the projects name seems to be "bmx-ng", we could even shorten it to "BNG" ...
## Collaboration

Original SVG file (done in Inkscape):
http://www.digidea.de/files/blitzmax/bmx_ng.svg

_Feel free to adjust it and present the output here in this issue. Usage in other (not "bmx-ng" related projects) projects (aka "using it as a logo for something else") is not allowed._

Ideas? Opinions?

**Comment by GWRon** [comment]
If you are not against the logo you might put it next to "maxide.bmx" so the new MaxIDE gets the new icon.
[maxide.ico.zip](https://github.com/bmx-ng/bmx-ng/files/2427918/maxide.ico.zip)

I think it helps if you have vanilla running next to it (other icon in the taskbar). Maybe MaxIDE should be renamed then too.. (MaxIDE NG or so?)

**Comment by GWRon** [comment]
Small
![blitzmaxng_logo](https://user-images.githubusercontent.com/2625226/47014629-16cbaf80-d14b-11e8-8602-7bccf21b8ed4.png)

Big (+ dark background):
![blitzmaxng_logo](https://user-images.githubusercontent.com/2625226/47015372-0fa5a100-d14d-11e8-8ccc-fcfff22b6525.png)

**Comment by woollybah** [comment]
The lighter blue is nice, but the rocket hiding the "x" a bit too much, I think.
Perhaps we could have the rocket available separately, and how would it look to have the rocket centered behind the text?

**Comment by GWRon** [comment]
![blitzmaxng_logo](https://user-images.githubusercontent.com/2625226/47024023-2fdf5b00-d161-11e8-9b6f-969e5af6c9ad.png)

**Comment by woollybah** [comment]
Something like the bottom-left, but it's probably too noisy? (and I'd lose the NG)
We kind of want something with the rocket logo (that we can then use for icons) and the text - together - however is the best way to have them together.

Or maybe the one on the bottom right (without the NG)... meh.
I suppose it depends if orange is "in" or not? :-p

Or maybe we can just have the blue text with a small orange one (or blue one with orange tail) above it (for the site landing page)...

*shrug*

**Comment by GWRon** [comment]
![blitzmaxng_logo](https://user-images.githubusercontent.com/2625226/47029162-278c1d80-d16b-11e8-8391-61848959f88d.png)
[blitzmaxng_logo.svg.zip](https://github.com/bmx-ng/bmx-ng/files/2483869/blitzmaxng_logo.svg.zip)


@ polluted images
This is why I used that transparent outline (looks "white" here but is in fact transparent). That NG ... can of course get left out.
While others prefer a mono colored logo (so it works black/white) I prefer two colors - as it allows to use two main colors on the website / elements. Eg. you could have blue headlines and orange list bullets or so.

**Comment by Kerntrick** [comment]
Definitely needs a new icon.  I use a custom maxide icon because I work in both ide's (mostly blide though)

![bmtb](https://user-images.githubusercontent.com/29359428/47029256-f9352080-d11f-11e8-8564-445748b8b062.PNG)

 If the new icon is completely different, then dropping the 'NG' is ok. 
I prefer the blue/white. (lower right)

**Comment by woollybah** [comment]
Thanks !
I've gone with the one on the lower-right for the main logo, and the tilted blue rocket for icons :-)

You may PR the site credits page to add a licence if you wish.
