### ISSUE TITLE
128bit datatypes

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmx-ng#10]
What's your thoughts on 128bit datatypes? specifically for SIMD/SSE type of work.

**Comment by woollybah** [comment]
I've no problem in general with adding new primitive types.
I already added size_t (which I've yet to use properly - for use in places like bah.regex where there is a lot of passing of size_t args, which is currently hacked to use Int or Long depending on architecture)

**Comment by woollybah** [comment]
You may also want matrix data 16-byte aligned, but I'm not sure how we'd do that from an array perspective...

**Comment by davecamp** [comment]
I'm building in an x64 environment so my thoughts may well be biased towards that. However, I've been scanning around the net for information and initially things looks promising, but I really don't know enough about the 'non desktop' environments to know for sure if it's a realistic option.
This link 'http://developer.android.com/ndk/guides/x86.html' seems to suggest some kind of support for android, and I read about a NEON coprocessor for some android environments which looks promising. And I'm also not so sure of any of this for the Pi variants.

At the moment I'm creating aligned memory on the heap and I try to keep any values in the xmm registers in c code as much as possible ( so that I can use the sse commands with them ). Vector and matrix math are getting a small overall 2x - 3x speed up using this approach - something as opposed to nothing. The loading to/from memory/registers is without doubt taking a speed hit here. Keeping things in the registers via native datatypes would be really great :+1:

**Comment by davecamp** [comment]
I understand that this may actually turn out to be a lot of work for what could be little in 'real term' gains, but still, I thought I'd ask.

**Comment by woollybah** [comment]
Do you still want this, or is it enough that array data is now 16-byte aligned?

**Comment by davecamp** [comment]
Having 'direct' simd/sse variables without the indirection of accessing an array can only be a great bonus :-)
It opens up all kinds of possible optimisations in all areas.

**Comment by woollybah** [comment]
Has been implemented for x64.
