### ISSUE TITLE
Change Icon?

### ISSUE THREAD

**Issue by llYuell** [bmx-ng/bmx-ng#100]
Hello, as change the icon, it is not easy for me to understand the help that is in English, speaks of a file settings, please some simple example.

**Comment by GWRon** [comment]
if your projectfile is "mygame.bmx" (so the binary becomes "mygame.exe") then just place an "mygame.ico" next to it - it should be used automatically.

**Comment by llYuell** [comment]
Thank you, it worked, another question, how do I put in the executable the information of the project, version number, company, etc.

https://www.blitzmax.org/docs/en/setup/win32/#application-settings

**Comment by GWRon** [comment]
`mygame.settings`
content as described in your link.

**Comment by llYuell** [comment]
Inside that file I copy this:  
Next to the ajecutable exe?
app.version.code=1
app.version.name=1.0.0
app.name=BlitzMax Application
app.comments=Comments
app.company=My company
app.description=App description
app.copyright=Copyright text
app.trademarks=All rights reserved

**Comment by GWRon** [comment]
Maybe try before posting - and then post here if it worked or not.

**Comment by llYuell** [comment]
It doesn't seem to be working.
![image](https://user-images.githubusercontent.com/47219982/64490453-7aa70d00-d222-11e9-8814-cf77ff07f571.png)

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/64490476-b6da6d80-d222-11e9-86db-5fbce3b3700f.png)

**Comment by GWRon** [comment]
Using the latest BCC/BMK/*.bmk-files or are you using the latest released package?

**Comment by llYuell** [comment]
I have no idea, I'm using the latest downloaded version of NG.

**Comment by GWRon** [comment]
Then ... you are using the latest released package - feel free to update bmk (and the provided .bmk-files like make.bmk and custom.bmk), bcc, pub.mod, brl.mod, sdl.mod

**Comment by llYuell** [comment]
Here ??

![image](https://user-images.githubusercontent.com/47219982/64490577-fd7c9780-d223-11e9-8452-b36bb120811d.png)
I mean open these files and run them?

**Comment by GWRon** [comment]
Compile bmk.bmx, copy the *.bmk files (only these who exist in blitzmax/bin already) and the bmk.exe
Compile bcc.bmx and copy the bcc.exe
Download brl.mod, pub.mod, sdl.mod ... aka updating the modules. Replace directories (do not just copy over files!).

Or wait for the next release to avoid running into complications.

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/64490691-441ec180-d225-11e9-8ab8-b1191899a7c5.png)
I think I'm going to follow your wise counsel. 
I tried to compile and I made a mistake. So I'd better wait for the next version.

**Comment by GWRon** [comment]
That error says you have "old code" running with "new bcc" (which requires `override` next to functions which override existing functions/method - or you uncheck the settings in MaxIDE (Build Options).

This is with a BCC from early August and a bmk.exe from June.

![settings](https://user-images.githubusercontent.com/2625226/64490746-89acb000-d260-11e9-9e18-bf8a29fbe0bf.png)

**Comment by llYuell** [comment]
Ok, correct compilation of bbc.exe and bmk.exe, I copied them to the Bin directory.

Where do I download the modules?

![image](https://user-images.githubusercontent.com/47219982/64490877-408c3a00-d227-11e9-9045-1ec1167ad466.png)

**Comment by GWRon** [comment]
https://github.com/bmx-ng

Sometimes I wonder how people are able to eat without a helping hand :smile:

**Comment by llYuell** [comment]
I think I'm always groping at this, but I've learned a lot from people like you. Thank you for your patience. 

#65

**Comment by llYuell** [comment]
Error. :(

![image](https://user-images.githubusercontent.com/47219982/64491596-e8a60100-d22f-11e9-8a0d-f62da240061a.png)

**Comment by GWRon** [comment]
Without further details I cannot help you.

If it does not highlight the error then this error:
- happens in a called DLL
- happens in a called code of included C files
- happens in a way that it kicks out the debugger

you might consider running it via "gdb" (included in BlitzMaxNG/Mingw...).
gdb -r path\to\your\binary

It then crashes and you type in "bt" (for "backtrace") it should spit out some lines of functions. If you compiled your stuff in MaxIDE with "GDB Debug Generation" (Developer Options) it would even contain "nice names" for BlitzMax functions.

**Comment by llYuell** [comment]
Ok, Solved here.

It didn't work because it had the Gui console App configuration activated, otherwise it doesn't paste the icon and doesn't collect information from the settings file. 

Much to learn, and immensely grateful for your patience.  
![image](https://user-images.githubusercontent.com/47219982/64492768-789e7780-d23d-11e9-9036-903a8e4ed0d1.png)

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/64492862-991b0180-d23e-11e9-9335-da596d90ada9.png)
