### ISSUE TITLE
Tutorial Sockets NG

### ISSUE THREAD

**Issue by llYuell** [bmx-ng/bmx-ng#102]
I'm learning about sockets and following the tutorial where I have to connect to the example via telnet.

But it doesn't work, I can't connect via telnet. 

Any suggestions?
![image](https://user-images.githubusercontent.com/47219982/65001938-403f0f00-d8b7-11e9-9d71-2bdb742d9c0e.png)

**Comment by llYuell** [comment]
A simple example of Gnet also does not work in NG. On the client side in the debugger pulls me the following message: Error sending outgoing packets: Result too large

**Comment by GWRon** [comment]
What error am I expected to see when running your server/client code?

to both code portions I added this on top:
```BlitzMax
SuperStrict
Framework Brl.gnet
Import Brl.GLGraphics
Import Brl.GLMax2D
Import Brl.StandardIO

```
To only import what is needed - maybe some other module interfers and makes some fuzz.... so framework keeps the other modules from being auto-imported.

**Comment by GWRon** [comment]
Another error in your code: your "hola" is printed on the same position ... if there were multiple gnet objects they would all draw on the same position.

```BlitzMax
        local objIndex:int = 0
        For Local obj:TGNetObject=EachIn GNetObjects( host,GNET_ALL )
                If obj.state()=GNET_CLOSED Continue
                If obj=me
                        SetColor 255,255,255
                Else
                        SetColor 255,0,0
                EndIf

                DrawText("Hola #"+objIndex, 0,20 + objIndex*15)

                objIndex :+ 1
        Next
```

**Comment by GWRon** [comment]
Checkout BlitzMax/samples/mak/gnetdemo.bmx

**Comment by llYuell** [comment]
My example only changes the color of the message "Hello" when the client is connected to the server, in the original blitzmax works correctly but in NG, I have problems. 

I have also copied the Mak example to the Blitzmax ng directory in the examples, as it does not come by default. But I have errors.

**Comment by llYuell** [comment]
I put the header as you mention both on the server and the client, but it still has errors.

The strange thing is that native BlitzMax does work.

**Comment by GWRon** [comment]
Learn to post the actual error - not just write stuff like "I have errors"

the sample uses doubles for params defined as float ... wrap the corresponding commands (sin(), rnd() ...) in "float()" so

SetScale float(Rnd(2,2.125)),float(Rnd(2,2.125))

and so on - it then compiles fine (just tried)

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/65184541-4fdf6480-da2b-11e9-89cf-4a0955d5139c.png)

When I put listen, on the server, it seems to work, but if I put connect, the client crashes.

**Comment by GWRon** [comment]
and where does it crash (debug build) ?

**Comment by llYuell** [comment]
Here:
![image](https://user-images.githubusercontent.com/47219982/65185016-51f5f300-da2c-11e9-81b5-b412094c2eb9.png)

**Comment by GWRon** [comment]
... now double click on "sync" in the top right - so to see where exactly.

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/65185170-9a151580-da2c-11e9-9ff9-dbd0e5bea231.png)

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/65185207-ab5e2200-da2c-11e9-9181-d17125c9f32a.png)

**Comment by GWRon** [comment]
I tried a debug build on my linux box -- and it takes a while and then "connect failed" in the console but no crash.

your "side box" mentions some empty memory addresses within the ENET object - so maybe the enet.mod is having flaws with NG / 64bit ?

**Comment by llYuell** [comment]
![image](https://user-images.githubusercontent.com/47219982/65186922-558b7900-da30-11e9-8f0c-2b5866045d5d.png)

I made a compilation in both 32 and 64, in both the client crashed

**Comment by GWRon** [comment]
The above is no crash but ... a message window based on "throw" - and this throwing happens because of the enet-event having an id of "0" instead of something useful - dunno why.

**Comment by llYuell** [comment]
It says that the connection has failed, I click on the Accept dialog box and the client crashes.

**Comment by GWRon** [comment]
This is no crash...

Add this inbetween your code:
Throw "my text"

And you will receive a box and then the application is closed.

You can do this if something happens in your program which is not foreseen by the developer.

**Comment by llYuell** [comment]
No work. :(

![Yue](https://user-images.githubusercontent.com/47219982/65294021-df1b7380-db22-11e9-800c-20c4757f5956.gif)

**Comment by llYuell** [comment]
This does work, which is not like sending messages, well at least for the moment. But if I can connect via telnet in windows to a simple test executable.

![image](https://user-images.githubusercontent.com/47219982/65357709-530a5a00-dbbd-11e9-8944-3259a7731c31.png)

![image](https://user-images.githubusercontent.com/47219982/65357728-6b7a7480-dbbd-11e9-94b0-d570a0b92afd.png)

https://en.wikibooks.org/wiki/BlitzMax/Modules/Networking/Sockets#CreateTCPSocket

**Comment by llYuell** [comment]
It also works in NG without problem, I can connect from telent. Then GNet has problems from NG.

What I have to find out is how to send messages, just that, but I don't find anything in the documentation, or at least my ignorance doesn't allow me to understand those commands for now.
![image](https://user-images.githubusercontent.com/47219982/65357879-c90ec100-dbbd-11e9-9309-480c9a50effa.png)

**Comment by GWRon** [comment]
So what does work: sending telnet->client and telnet->server? can you send from server->telnet? (reply) ?

**Comment by woollybah** [comment]
enet and gnet have been updated.
