### ISSUE TITLE
Goto

### ISSUE THREAD

**Issue by nikikust** [bmx-ng/bmx-ng#104]
Hi! Goto throw the Compile error
Code from example (.goto.bmx):
```
Print "one"
Goto here
Print "two"
#here
Print "three"
```

 - OS: Win7
 - bcc/bmk/maxide Version [e.g. 0.105]

**Comment by woollybah** [comment]
`Goto` is not a supported statement in this version of BlitzMax, and was only supported in the "non-Strict" builds of the legacy compiler.

We suggest you instead use the many different types of flow control available in BlitzMax to accomplish the same task.

**Comment by nikikust** [comment]
Thank you for your answer. I asked about this because i found my old project and I wanted to compile It 😀
