### ISSUE TITLE
Global var and function bug

### ISSUE THREAD

**Issue by mingwya** [bmx-ng/bmx-ng#105]
'This code:

SuperStrict

Global ar$[]

Function Add(s$, array$[])
	array:+[s]
End Function

Add("Hello!",ar)
Add("Albert!",ar)

For Local i% = 0 Until ar.Length
	Print ar[i]
Next
Print ar.Length

'---
'output 0

**Comment by HurryStarfish** [comment]
That's not a bug. Behaviour is the same as in BlitzMax vanilla.
`array :+ [s]` is equivalent to `array = array + [s]`. You're creating a new array and assigning it to the `array` variable. This does not modify the `ar` variable you passed to the function. If you want it to do that, you gotta declare the parameter as pass-by-reference: `Function Add(s$, array$[] Var)`

**Comment by mingwya** [comment]
thanks!

**Comment by GWRon** [comment]
Can you please close the issue?
