### ISSUE TITLE
BlitzMax RaspberryPi v0.115.3.40 - undefined reference to `glDisable'

### ISSUE THREAD

**Issue by imaan2005** [bmx-ng/bmx-ng#113]
I have installed BlitzMax RaspberryPi v0.115.3.40 on the latest Raspbian OS but after compiling the firepaint sample, i keep getting compile error with the following message:
BlitzMax/mod/sdl.mod/gl2sdlmax2d.mod/.bmx/main.bmx.debug.raspberrypi.arm.c:3051: undefined reference to `glDisable'
BlitzMax/mod/sdl.mod/gl2sdlmax2d.mod/.bmx/main.bmx.debug.raspberrypi.arm.c:3051: undefined reference to `glEnable'

I already have installed the following packages:

sudo apt install g++ libglu1-mesa-dev libasound2-dev libfreetype6-dev libxpm-dev libxft-dev libxxf86vm-dev libpulse-dev libopenal-dev libwebkitgtk-dev libaudio-dev libesd0-dev libwebkit2gtk-4.0-dev libgtk-3-dev

I have tried it on both RPI3 and RPI4 but i get the same result on both. it looks that Blitzmax can't find the OpenGl but I see that all OpenGL files are already installed and available in this location: /usr/include/GL/

I appreciate it if you suggest me what to do. 
Thanks

**Comment by woollybah** [comment]
The latest release should resolve this issue.
