### ISSUE TITLE
[Feedback] BlitzMaxNG on aarch64

### ISSUE THREAD

**Issue by AXKuhta** [bmx-ng/bmx-ng#114]
I'm running a 64 bit build of BlitzMaxNG on my phone in a Linux Deploy container with Debian 10. It all works flawlessly, although getting MaxIDE to compile required a few little changes:

1. Adding aarch64 path for glib header
```
diff --git a/gtk3maxgui.mod/gtk3maxgui.bmx b/gtk3maxgui.mod/gtk3maxgui.bmx
index e4c46b5..ef0f0f7 100644
--- a/gtk3maxgui.mod/gtk3maxgui.bmx
+++ b/gtk3maxgui.mod/gtk3maxgui.bmx
@@ -35,7 +35,7 @@ ModuleInfo "History: Implemented some missing functionality."

 ?Linux
 ' glib
-ModuleInfo "CC_OPTS: -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib64/glib-2.0/include"
+ModuleInfo "CC_OPTS: -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/lib64/glib-2.0/include"
 ' gtk
 ModuleInfo "CC_OPTS: -I/usr/include/gtk-3.0  -I/usr/lib/i386-linux-gnu/gtk-3.0/include"
 ' cairo
diff --git a/maxguitextareascintilla.mod/maxguitextareascintilla.bmx b/maxguitextareascintilla.mod/maxguitextareascintilla.bmx
index 0e5fe88..ca637aa 100644
--- a/maxguitextareascintilla.mod/maxguitextareascintilla.bmx
+++ b/maxguitextareascintilla.mod/maxguitextareascintilla.bmx
@@ -48,7 +48,7 @@ ModuleInfo "CC_OPTS: -DGTK"
 ModuleInfo "CC_OPTS: -std=c++11"

 ' glib
-ModuleInfo "CC_OPTS: -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib64/glib-2.0/include"
+ModuleInfo "CC_OPTS: -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/lib64/glib-2.0/include"
 ' gtk
 ModuleInfo "CC_OPTS: -I/usr/include/gtk-3.0  -I/usr/lib/i386-linux-gnu/gtk-3.0/include"
 ' cairo
```

2. Enable including NEON code for libpng (Or else it fails to link)
```
diff --git a/libpng.mod/libpng.bmx b/libpng.mod/libpng.bmx
index 8779b3d..33d79fe 100644
--- a/libpng.mod/libpng.bmx
+++ b/libpng.mod/libpng.bmx
@@ -51,7 +51,7 @@ Import "pngwio.c"
 Import "pngwrite.c"
 Import "pngwtran.c"
 Import "pngwutil.c"
-?ios
+?ios Or raspberrypi
 Import "arm/arm_init.c"
 Import "arm/filter_neon_intrinsics.c"
 ?x86
```

The process of getting an aarch64 build of BlitzMaxNG is roughly as follows:
1. Have an aarch64 linux installation (Be it a Raspberry Pi 3/4 or an Android phone with Linux Deploy)
2. Run the following
```
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libc6:armhf
```
3. Now you should be able to run `bmk` and `bcc` from the 32 bit Raspberry Pi build, and that allows you to compile 64 bit versions of them with native gcc

I know that's probably not the best way to do it, since new `bmk` still thinks it's made for a 32 bit Raspberry Pi, but it functions flawlessly, and that's good enough for me.

**Comment by woollybah** [comment]
Nice! 😺 
Thanks for experimenting with it.
I'll look into applying your patches.

You should be able to use `-g arm64` to make BlitzMax understand the build is for 64-bit - which should affect code that uses things like `?Ptr64`.

There is an undocumented mode for `bmk` that allows you to generate "bootstrap" sources for a given target/arch. It's useful for getting `bcc` and `bmk` onto a new platform.
I need to document it and upload some resources for it.

**Comment by AXKuhta** [comment]
I can see you added these changes, so thank you!

I can also confirm that building with `-g arm64` works, though it still needs `-l raspberrypi` to be specified, otherwise it will try to build for generic linux instead and will try to pass `-m64` to the gcc, which is not a valid option on arm.

Also here's a little change to have arm64 option in MaxIDE:
```
diff --git a/maxide.bmx b/maxide.bmx
index f1e40e5..e9168d3 100755
--- a/maxide.bmx
+++ b/maxide.bmx
@@ -7727,6 +7727,7 @@ Type TCodePlay
                                EnableMenu arm64enable
                        Case MENURASPBERRYPIENABLED
                                EnableMenu armenable
+                               EnableMenu arm64enable
                        Case MENUANDROIDENABLED
                                EnableMenu x86enable
                                EnableMenu x64enable
```

**Comment by AXKuhta** [comment]
A bit of an addendum, because I'm having trouble with the latest builds of BlitzMax for Raspberry Pi:
Following builds do not work properly on aarch64:
- v0.129.3.45.rpi.arm
- v0.128.3.45.rpi.arm

They crash with SIGBUS when attempting to compile any meaningfully large file.

Following build works fine:
- v0.115.3.40.rpi

It is able to compile the latest versions of bmk and bcc, but it's important to use `-l raspberrypi -g arm64` otherwise the produced executables crash with `*** stack smashing detected ***`

Make sure to never drop the `-g arm64` argument if still supplying `-l raspberrypi`, otherwise it _will_ switch back to 32 bit builds and produce crashing binaries. There also appears to be a `raspberrypi64` target but it's seemingly obsolete and non-functional: https://github.com/bmx-ng/bmk/blob/master/bmk_config.bmx#L122

Here's my build should you want it: https://drive.google.com/file/d/1kFUXePg2pza_6jNC7T5zPFYZbyi5ZQlR/view?usp=sharing; seems to self-reproduce fine.

**Comment by AXKuhta** [comment]
There's also some minor breakage on GCC 10 with the v0.115.3.40 version due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678; you'll have to comment out some code related to OnDebug to get it to compile. Doesn't seem to happen with the newest code.

**Comment by woollybah** [comment]
I've fixed the issue where it used `?raspberrypi64` instead of `?raspberrypiarm64`. It will now correctly build target `arm64` for an arm64 native `bmk`.

I suppose we could have an arm64 specific release at some point.


FYI
There's a "bootstrap" function within `bmk`, that allows you to generate sources that can then be compiled on a specific target.
For example, you can run it Windows to create scripts to compile arm64 bcc and bmk on a 64-bit Pi. I just did this for Ubuntu 20.10 that I had just installed on a new SD card.
If you want to give it a try, your BlitzMax installation needs to be set up correctly. Have the (latest?) sources for bcc and bmk in the BlitzMax/src folder.
Copy the `bootstrap.cfg` file from `BlitzMax/src/bootstrap` (this should be part of the standard release) to the BlitzMax/bin folder.
Edit the file - uncomment the target you'd like to build - so, for example, the line with `t    raspberrypi    arm64`
And then run `bmk makebootstrap`

This will create a folder `dist` and generate lots of source, and some scripts.
Zip it up, and drop it onto a suitable target system.

Navigate to the `dist/bootstrap/src/bcc` folder and run the relevant `build` script using the `source` command. eg. `source bcc.console.release.raspberrypi.arm64.build`
After a successful build, you should have an executable `bcc` that you can drop into the `BlitzMax/bin` folder.
... repeat for `bmk`.

Useful for targeting new platforms - such as I did for Haiku.
