### ISSUE TITLE
Launching MaxIDE on Linux: Segmentation fault 

### ISSUE THREAD

**Issue by Nju79** [bmx-ng/bmx-ng#115]
Hi there,
when I want to start the MaxIDE (v0.116.3.41) I can see the splash screen for a moment, then the program is closing. In the terminal I get the error: Memory Access Error

I'm using Manjaro 18.1.5 (64Bit) with XFce.

For testing I downloaded the older one of BlitzMax (v0.105.3.35). In this case the program starts normaly. But when I click on New File the gui is crashing (same error). Exactly the same when I will open a file -> Selected one and clicking on "open". 

I think, there is a bug when MaxIDE will creating a new tab.

Best regards :)

**Comment by GWRon** [comment]
And a very old build?

If that runs then you might be able to build the newer as debug build and see the actual error.

**Comment by Nju79** [comment]
Okay, I tested some other releases. Here are the results:

v0.116.3.41:
Splashscreen for milliseconds, then crash
memory access error

v0.99.3.31: Will open the ide, click on File->New -> crash
memory access error

v0.81.3.15: Splashscreen for milliseconds, then crash
libpng warning: iCCP: known incorrect sRGB profile
memory access error

I checked the old Community Edition of MaxIDE (original release v1.15) too and this IDE works without crashes.

**Comment by GWRon** [comment]
The community one uses fltk while the NG ones utilize GTK.

If you build newer maxide with that community one then you should be able to see where it crashes/segfaults.

**Comment by Nju79** [comment]
Can you give me a short step by step guide to do this?

**Comment by woollybah** [comment]
It may be more useful to try compiling your own, since the source of maxide should be available in the `src` directory with the release.

* Open Terminal and navigate to your BlitzMax/bin dir
* Run the following command from there :
```
./bmk makeapp -a -r ../src/maxide/maxide.bmx
```
Assuming you have all the necessary packages installed, that should create you a `maxide` binary in `src`.
You can then copy that to the main directory..
```
cp src/maxide/maxide ..
```
and then try running it...
```
../maxide &
```
If that *doesn't* work, and you have the same access error, then there's something else wrong that I am unaware of.

**Comment by GWRon** [comment]
if it doesn't work you can use your "community edition MaxIDE" (rename to "MaxIDE_community" or so, place it into "BlitzMax" - so next to the not working "MaxIDE" binary). Then start the community edition MaxIDE and open up the file "src/maxide/maxide.bmx". In your running MaxIDE go to the options and check "debug". Then hit the "Compile and run" (or the flying rocket icon) and let it compile.

Once it executes it will then show in which area of the code it is failing.


But first do as Brucey suggests - he has more knowledge of it than me so better trust him first.

**Comment by Nju79** [comment]
@woollybah 
Thank you for your guide. I could compile maxide without errors. 

Now the bad news: I couldn't open the ide. Same error as I wrote earlier: Splashscreen for milliseconds, then crash.

**Attention:**
For my own fault I translated the error message wrong. Instead of "memory access error" the correct error message is "Segmentation fault".

To narrow down the error I used VirtualBox to install fresh versions of Manjaro:

Manjaro 18.1.5 (64Bit) with Gnome: IDE is working(!)
Manjaro 18.1.5 (64Bit) with XFce: IDE is NOT working

@GWRon 
U wrote, NG is utilizing GTK. I will check tommorow if `pacman -Qi gtk2 && pacman -Qi gtk3` with Gnome and XFce is showing anything unusual. Stay tuned. :)

**Comment by woollybah** [comment]
Hi, I will try to set up a similar system to test it myself.

**Comment by Nju79** [comment]
Okay, I've tested some points.
First: There was nothing unusualy. I've installed missed gtk-packages but got the error message again.
Second: I tried to "build and run" the sourcecode with the community_edition at the latest source (@GWRon) . Compiling works (as I wrote earlier), but running stopped in method `SetDefaults()` in line `editfontname$=FontName(TGadgetStyle.fntLibrary[GUIFONT_MONOSPACED])` with error message `Unhandled Exception:Attempt to access field or method of Null object`. 

I don't know how this library works, but in my opinion he can't find a font in the Looking-Function for MonoSpace. I've installed terminus as Monospace bitmap font. Which Font the function is looking for?

**Comment by Nju79** [comment]
Okay, tested more. When I change `GUIFONT_MONOSPACED` to `GUIFONT_SYSTEM` the ide works. There a missing a fonttype I think.

**Comment by GWRon** [comment]
I assume it is not directly a specific font...but the lookup for a font "kind" fails.

I am not sure but I had such a font lookup issue some years ago... 
Also I am pretty sure that this is a helpful hint now and that maybe Brucey or others can now help with new ideas.

Maybe even googling can now help.

**Comment by GWRon** [comment]
Will have to search my mails but I am sure to have somewhen communicated with Brucey about an issue with lookupguifont(). Must not be the same or even useful but there was something.


Aside of that: do you have the font "Courier" installed? According to maxgui-docs it is the default font for "monospaced" on linux.

**Comment by Nju79** [comment]
@GWRon 
Okay, I installed and tested several fonts (on my main system) listed by `https://wiki.archlinux.org/index.php/Fonts` and after I installed the package `gnu-free-fonts` (Category "Monospaced") the ide works.

I verified this in VM with XFce* and installed the same package: ide works
In my VM with Gnome* this package isn't installed, but the ide is working too.

I can probably not install any font package from the monospace category, because when I install `ttf-hack` the ide don't work in XFce*.

Finally, this is the workaround and I think, this should be add in the docs on `www.blitzmax.org`.

*with Manjaro

**Comment by GWRon** [comment]
According to 
https://github.com/bmx-ng/maxgui.mod/blob/febe68f7a89009758fca554cc810435aff2dd8d1/maxgui.mod/driver.bmx#L58

It requries "Lucida" as font-face to be installed on Linux OS ...

```BlitzMax
		Select pFontType
			Case GUIFONT_MONOSPACED
				?Linux
				Return LoadFontWithDouble("Lucida",pFontSize,pFontStyle)
				?MacOS
```

Either we should add the fonts as required dependencies in the Linux instructions  - or we could provide a base-font with NG - or we fall back to some "default font" in the same way as done in the gtk3 driver:
https://github.com/bmx-ng/maxgui.mod/blob/febe68f7a89009758fca554cc810435aff2dd8d1/gtk3maxgui.mod/gtkgui.bmx#L459
