### ISSUE TITLE
MaxIDE in latest BlitzMax Win32 v0.118.3.41 release built in console mode

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/bmx-ng#117]
Hi Brucey, thanks for the new releases, but I think "BlitzMax Win32 v0.118.3.41" and the current blitzmax.org versions (64-bit at least) have been built in console mode, possibly from wrong current directory too (?), as MaxIDE has no icon, the toolbar is missing icons and it opens a console window behind:

![console](https://user-images.githubusercontent.com/1781537/76736495-d072e980-675e-11ea-9b6f-46665ead0c30.jpg)

I'm on Windows 7, 64-bit.

**Comment by woollybah** [comment]
Hi there.
Yes, my shiny new auto-build system is only as good as user who runs it - which unfortunately was me, and which turns out to be the weak point in the build chain. 😞 

I've rebuilt them with a newer version of BlitzMax (118 instead of 105!), which appears to have resolved (at least) the issue you've encountered.

At least the build/release script is improving :)

**Comment by DruggedBunny** [comment]
Hi Brucey, that looks much better, MaxIDE runs as expected... but if I try "out of the box" to run a simple `Print "Hello"` it fails on `pub.jansson`, and it looks like that's been removed/moved.

I tried putting an older copy in, but get:

```
Building untitled1
[ 23%] Processing:untitled1.bmx
[ 86%] Compiling:untitled1.bmx.gui.debug.win32.x86.c
In file included from C:/Users/James/Desktop/BlitzMax_win32_0.118.3.41(1)/BlitzMax/tmp/.bmx/untitled1.bmx.gui.debug.win32.x86.c:1:
C:/Users/James/Desktop/BlitzMax_win32_0.118.3.41(1)/BlitzMax/tmp/.bmx/untitled1.bmx.gui.debug.win32.x86.h:46:10: fatal error: pub.mod/jansson.mod/.bmx/jansson.bmx.debug.win32.x86.h: No such file or directory
 #include <pub.mod/jansson.mod/.bmx/jansson.bmx.debug.win32.x86.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Build Error: failed to compile (1) C:/Users/James/Desktop/BlitzMax_win32_0.118.3.41(1)/BlitzMax/tmp/.bmx/untitled1.bmx.gui.debug.win32.x86.c
Process complete

```
You know what they say: fail fast and... something... and then it'll probably work. Something like that.

**Comment by DruggedBunny** [comment]
Oh, I used the latest Windows combined 32/64 release.

**Comment by GWRon** [comment]
Brucey forgot to add "text.mod" which now contains all this json, xml ... stuff.
https://github.com/bmx-ng/text.mod

Imho it needs a further cleanup as it now mixes "libs" and "implementation" (maybe the libraries should have a "lib" prepended to group them somehow.

**Comment by DruggedBunny** [comment]
GWRon, not sure if the Edits were for me, but I just ran Print "Hello" in the unaltered new release. I'll try bringing in text.mod and see what happens, thank you!

**Comment by DruggedBunny** [comment]
OK, I just started over with fresh install:

1) Removed pub.jansson;
2) Cloned pub.text;
3) Ran Print "Hello".

... but it can't find pub.text for some reason!

(Oh, and brl.json isn't present in the latest release.)

![pub text](https://user-images.githubusercontent.com/1781537/76808332-52a2f280-67df-11ea-9e58-b2b0654f1ff9.jpg)

**Comment by DruggedBunny** [comment]
Should there be a text.bmx in pub.text, as it's just sub-folders of mods?

```
 Directory of C:\Users\James\Desktop\BlitzMax_win32_0.118.3.41(1)\BlitzMax\mod\p
ub.mod\text.mod

[.]           [format.mod]  [json.mod]    [regex.mod]
[..]          [jansson.mod] [mxml.mod]    [xml.mod]
.gitignore    [jconv.mod]   README.md
               2 File(s)             79 bytes
               9 Dir(s)  17,740,537,856 bytes free

```

**Comment by DruggedBunny** [comment]
OK, all working now, including the GLFW update, after sticking text.mod in the root mod folder like so:

https://github.com/bmx-ng/bmx-ng/commit/259757f4ebf32455ffdcb36b4f2ee812a4c69a08

Thanks, Brucey/all!
