### ISSUE TITLE
Android build - dlopen failed: cannot locate symbol "bbSystemPostSyncOp"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#12]
When executing an armevabi-build (same for other targets) on my android 5.1:

```
E/art     ( 1100): dlopen("/data/app/com.blitzmax.android-1/lib/arm/libcolorize.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "bbSystemPostSyncOp" referenced by "libcolorize.so"...
E/AndroidRuntime( 1100): Process: com.blitzmax.android, PID: 1100
E/AndroidRuntime( 1100): 	at com.blitzmax.android.BlitzMaxApp.<clinit>(BlitzMaxApp.java:10)
```
that `bbSystemPostSyncOp` sounds like it is coming from BlitzMax (bb***).

**Comment by GWRon** [comment]
That function is defined in "brl.mod/systemdefault.mod/system.linux.bmx" but disabled for android-builds via `?Not android` ... but why is it required then?

Ah ok ... it is used in "timer.linux.c" - which is imported by "brl.mod/timer.mod/timer.bmx" - for __all__ linuxes.

**Comment by GWRon** [comment]
I recognized, the error comes up as soon as I import "brl.retro" (think it imports the timer...).

So some of my samples still work fine on android, but as soon as "retro" was imported - problem occours.

**Comment by woollybah** [comment]
The split out of BRL.Timer should have solved this issue now.

**Comment by GWRon** [comment]
Examples of course need adjustments, so replacing `Import Brl.Timer` with:

```BlitzMax
Import Brl.Timer
?bmxng
Import Brl.TimerDefault
?
```

**Comment by woollybah** [comment]
Unless you are using SDL, in which case you should import SDL.Timer instead.

**Comment by GWRon** [comment]
Hmm we certainly need some kind of #defined and #define...

If you could define ?conditionals or something like ?vars(sdl) ... then you could use

?sdl
DoSDLstuff
?not sdl
StuffForVanillaOrNotSdl
?
