### ISSUE TITLE
MaxIDE: Samples/Source links lost if main folder renamed

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/bmx-ng#121]
Hi Brucey,

_NB. Low priority! Not important to me, just 'nice to fix', especially for any new users._

Latest release seems to be working well! I'm using the combined BlitzMax Win32 v0.128.3.45 x86/x64 Win32 release.

However, I noticed that if I rename the main BlitzMax folder to anything else, it loses the links to Samples, Modules Source and BlitzMax Source:

![linkslost](https://user-images.githubusercontent.com/1781537/95267461-3a52fd80-082d-11eb-8b14-2b91e6c7f437.jpg)

Note the lower inset screenshot was taken after closing the IDE, renaming the same folder to BlitzMax2 and running the IDE again.

I call mine BlitzMaxNG as I have some other versions installed... I believe it did this before and I just haven't picked up on why they weren't there, but I've checked and naming the folder back to BlitzMax fixes the links on re-running the IDE.

Thanks for the update, looking good so far!

**Comment by woollybah** [comment]
I'm pretty sure it has always been this way.
The configuration is stored in the file `cfg/ide.ini`, using full paths for file/dir references.

As a "quick fix", you could rename the parts that have changed, which would fix the issue for the next opening of the IDE.

I suppose it would be possible to add some kind of "variable" that represents the base folder, and default the standard folders to be prefixed with that.

**Comment by woollybah** [comment]
Also, renaming the folder before you start the IDE for the very first time would also prevent the issue you are seeing ;-)

**Comment by DruggedBunny** [comment]
Fair enough, assumed it was a runtime check by the IDE! Thanks for looking.

**Comment by GWRon** [comment]
We could change it to become a runtime like check on startup

-> if it cannot find the file, do the "init"-part which would be done if no config file existed
