### ISSUE TITLE
Compiler crashes when module uses TArrayList from brl.collections

### ISSUE THREAD

**Issue by KrautApps** [bmx-ng/bmx-ng#139]
**Description**
When using a TArrayList in a module the compiler crashes. Note: This only happens when doing this in a module apparently.

**To Reproduce**
Use this test module and import it in a simple app, you don't need to instantiate it:

Test-App
```
SuperStrict

Import test.test
'That's it, nothing more needed ;)
```
Module mod.test/mod.test/test.bmx:
```
SuperStrict

Module test.test

Import brl.collections

Type TTest
Private
  Field bla:TArrayList<Int>

Public
  Method New()
  End Method
End Type

```

**Expected behavior**
Compiler shouldn't crash.

**Version information (please complete the following information):**
 - OS: Windows 10
 - MaxIDE 1.56 [ng] (x64)
 - bcc[ng] Release Version 0.129
 - bmk 3.45 mt-win32-x64 / gcc 080100 (cpu x 16)
 - gcc/g++ version 8.1.0

**Comment by GWRon** [comment]
running latest bcc, bmk, brl, pub ... mods

- copied your code into "mod/test.mod/test.mod/test.bmx"
- pasted this into a new maxide document:
```
SuperStrict

Module test.test

Import brl.collections

Type TTest
Private
  Field bla:TArrayList<Int>

Public
  Method New()
  End Method
End Type
```

output:
```
[100%] Linking:untitled1.debug
ar: Erzeugen von /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/collections.mod/collections.debug.linux.x64.a
ar: Erzeugen von /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/test.mod/test.mod/test.debug.linux.x64.a
Executing:untitled1.debug
Hello World

Process complete
```

So it might require updated bcc + mods for you.

**Comment by KrautApps** [comment]
Thanks @GWRon, that indeed fixed it. So consider this solved. Thanks for your help!
