### ISSUE TITLE
[FR] DateTime module

### ISSUE THREAD

**Issue by thareh** [bmx-ng/bmx-ng#145]
**Is your feature request related to a problem? Please describe.**
A proper DateTime module for BlitzMax would be swell!

**Describe the solution you'd like**
A conversion of BaH.Boost, BaH.BoostLocale & BaH.DateTime would be good, I've made it compile myself but I don't know if I've done something wrong or if there's a bug somewhere but it crashes for me after a while using the sample below.

```
Framework BRL.Blitz
Import BaH.DateTime
Import BRL.FileSystem
Import BRL.StandardIO

Global timeZone:TTimeZone = TTimeZone.Create("UTC+2")

Function FileTimeStr:String(path:String, format:String)
	Local time:Long = FileTime(path)
	
	If Not time
		Return Null
	EndIf
	
	Local timeFrom:TTime = TTime.CreateFromFileTime(Int(time))
	Local dateTime:TLocalDateTime = TLocalDateTime.CreateFromTime(timeFrom, timeZone)
	Local timeTo:TTime = dateTime.localTime()
	Return timeTo.format(format)
EndFunction

For Local i:Int = 0 Until 100000
	Print i + " -> " + FileTimeStr("Foo.bmx", "%Y-%m-%d")
Next
```

Thanks!
-- Thareh

**Comment by HenriVi** [comment]
Hi,

I could not get your example to crash on my Windows machine.

You could try my version of bah.datetime + boost for ng to see if it crashes for you (see attached).

[bah.datetime + boost.zip](https://github.com/bmx-ng/bmx-ng/files/9484696/bah.datetime.%2B.boost.zip)

-Henri

**Comment by thareh** [comment]
Hey,

Thanks for your reply, I tried your version of the modules but it crashes in just the same way I'm afraid.

Weird that it doesn't crash for you though, I'm using Windows as well - perhaps if you increase the iterations it will crash for you too?

Thanks,
-- Thareh

**Comment by GWRon** [comment]
If stuff crashes for one but not another it might indicate a "GC'd while in use" thing. The GC decides on its own when to collect - for some this happens earlier and for others later.
Also the old memory address of a "freed" object can still point to "valid" data.

So maybe as a first step: Disable the GC (`GCSuspend()`) and check if it still fails - if not, then something is collected while it is in use somewhere (or one of their internal data)

I have bug reports of users for my game - which runs flawless here (and many others) but not for them. We had 32bit-issues, 64bit issues (Long + Reflection ...) and all this stuff. Hope you narrow down the issue faster than I do (fighting my game's bugs).

**Comment by HenriVi** [comment]
Brucey just added the new boost.mod for ng that has the datetime.mod inside with all the fixes, so try that out.

**Comment by thareh** [comment]
Indeed, thanks for the feedback! 👍
