### ISSUE TITLE
Add "Array Slide"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#150]
@woollybah just added some utf8stream-encoding wrapper and in the commit I suggested to use `bbmemmove()` when he moved "up" elements in an integer array.

We have "aray slicing" to split arrays ... wouldn't it be a "good" idea to also have "array sliding"? 

So each time you want to "pop first" and "add last" to an array you would simply be:

```BlitzMax
Local first:int = arr[0]
Local last:Int = 1234
SlideArray(arr, 1) 'move by 1 element, second becomes first, third becomes second ...)
arr[arr.length-1] = last
```
Or similar.

Dunno if GCC optimizes stuff like manual iteration and movement already ... and how big an array must be that memmove is faster than iteration and assignment.

Edit: As with "memmove" we do not resize the array (which might be some interesting thing for a "popArray()" too) it should have no issues with `staticarray`

**Comment by HurryStarfish** [comment]
Why not just use a ring buffer?

**Comment by GWRon** [comment]
Maybe because it is not meant to be refilled ... 

I was just asking as I saw this code in the utf8 thing and it looked like something which could benefit from sliding arrays.

But looking at brl.objectlist I saw there is already `ArrayCopy()` which already does it ... dunno if the inners of this function (in blitz.mod/blitz_array.c) are more expensive then the 3 checks in the utf8stream-file (generated c-code wise).

Anyways ... I think this is already good enough for "arrayslide" ...  I was just not aware of `ArrayCopy()` (especially as the naming does not expose that it can work on "src = target" array constellations).

**Comment by HurryStarfish** [comment]
> Maybe because it is not meant to be refilled ...

I thought the idea was that the size of the array doesn't change? If it does, you might as well use slicing (since you would have to create a new array anyway) or another data structure. But if it doesn't, then a ring buffer should be much more efficient than copying array contents around.

**Comment by GWRon** [comment]
Dunno if the "extras" to setup a ring buffer for scenarios "less often used" (things happen rarely and only in these cases you "pop" an element) are more costly than using a function call doing it for you.
