### ISSUE TITLE
Compile Error: Can't find interface for module 'brl.polygon' /sdl.mod/sdlrendermax2d.mod/sdlrendermax2d.bmx;41;0]

### ISSUE THREAD

**Issue by zarosath** [bmx-ng/bmx-ng#155]
**Describe the bug**
Its a compile error

**To Reproduce**
build modules with BlitzMax_linux_x64_0.138.3.53 release

**Expected behavior**
successful compile

**Screenshots**

**Version information (please complete the following information):**
 - OS: [Ubuntu 22.04.2
 - BlitzMax_linux_x64_0.138.3.53

**Additional context**
i looked in the brl.mod folder, there is no polygon mod

**Comment by zarosath** [comment]
i saw your commit, i changed it to math.polygon and it compiles successfully.

**Comment by GWRon** [comment]
Maybe close this issue if it is no longer valid.
