### ISSUE TITLE
macos-arm64 weekly build

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmx-ng#171]
Hiya,

Are there any plans to include macos-arm64 in to with the weekly release build?

Thanks.

**Comment by crushroll** [comment]
Please release a build for M1 or M2. I have spent hours trying to build the thing, tried all the suggestions, but had yet to successfully build the whole thing. Can you please provide a build?! Thanks.

**Comment by davecamp** [comment]
There is a release here that requires a bootstrap build :
https://github.com/bmx-ng/bmx-ng/releases/tag/v0.138.3.54.macos.arm64

If you have any problems feel free to post back here, or even better would be to join the discord server at
https://discord.gg<forward slash>4F676sVn
(Invite will expire in 7 days)

**Comment by GWRon** [comment]
The one davecamp suggested should also be no binary build but scripts plus required sources.

Am 29. September 2023 12:30:57 MESZ schrieb crushroll ***@***.***>:
>That's not a binary build, it's source that I've tried to build for hours
>and can successfully get it to work. I followed all the issue resolutions
>plus more, but no success. Can someone build it to binaries and upload a
>zip? Thanks
>

**Comment by crushroll** [comment]
If anyone has an M1 mac, and has successfully built a binary version, can you please upload the binary version to the BlitzMax site, or here. I have downloaded the source with the scripts and tried to build it, but keep coming up against the C99 issue. I have added std=C90 to the scripts and to source .bmx files as per fixes published, but can't get it to successfully complete.

**Comment by crushroll** [comment]
I gave it another try today, and finally got it to build.
I followed the fixes as per https://github.com/bmx-ng/bmx-ng/issues/169 but also had to add the -std=c90 to all files that are part of zlib, not just gzlib, gzread and gzwrite.
As for the zlib.bmx fix, I need to remove the ?ios and ?, so CC_OPTS: -std=c90 was used for all builds.
When I ran the build_dist.sh file it failed with several missing files. To fix this, I had to copy config.bmk core.bmk and make.bmk from BlitzMax/dist/bootstrap/src/bmk to BlitzMax/bin, then is worked.
Finally, for some reason it wouldn't copy the main maxide executable into bin, so I deleted the one that was already there and copied it manually from BlitzMax/src/maxide/maxide.app ro BlitzMax/bin.

**Comment by crushroll** [comment]
Now there's an issue with actually building in BlitzMax.
Had to add ModuleInfo "CC_OPTS: -DHAVE_UNISTD_H -std=c90" to BlitzMax/mods/brl.mod/glgraphics.mod/glgraphics.bmx
You may need to do this other mods as well, if you come across the C99 issue.

**Comment by davecamp** [comment]
@woollybah
Thank you for adding to the weekly build
