### ISSUE TITLE
new home for NG and discussions?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#18]
As skidracer/mark seem to have shut down the blitzmax.com forums (or just moving it / preparing readonly state) I want to use this central place to discuss about the future of NG social places.

col (or so) registered blitzng com which is good if we intend to have a place for all blitzers. If we want to cut loose ends (as mark sibly does) we could move to the existing bmxng site.

Is there a need for a forum at all? I think so at least.

Is there a need for a portal/website? I think at least for easy downloads, an about page and maybe some other automateable content (lastest twitter, github issues...).

What do you think?

**Comment by MikeHart66** [comment]
Quite a few moved over to this forum at http://www.syntaxbomb.com which Col has resetup again.

**Comment by GWRon** [comment]
I knew about syntaxbomb ...and while I like the name for an "indie coder board" it might not suit to a "blitz projects" website. If eg. people want the old forum posts this wont look good (waters old content of the forum). Of course adding the old posts is something discussworthy too (if the new home becomes the legal successor of blitzbasic.com it would be legal as we would not duplicate the forum but "move" it)

Similar I think about socoder.net.

Both could be a home for the normal social interaktion but they do not fit to a project-oriented website.

As I do not know what is really the thing you all (and of course at least Brucey as father of NG) want.

**Comment by woollybah** [comment]
Hallo :-)
I know, I need to sort something out properly. I was hoping I'd have until the end of the month to get organised, but Skid unfortunately appears to have lost the plot and nuked the forums. It's all very sad really.

As for what next, I think I'd like a site with something like a [Sphynx](http://www.sphinx-doc.org/en/stable/)-based design (pages based on .rst, etc), with downloads, proper documentation, examples, etc,  and I suppose a forum too.

I honestly don't like the idea of fragmenting the community in the way it appears to be going - suddenly you have X number of forums all over the place, and no-one really knowing where to find the best help.

**Comment by GWRon** [comment]
Would you like to have something like bmxng.blitzng.com? Means all projects get their own "page" and designs and...
Or should we enforce a common standard..so all projects have documentation, examples,... and share a forum.


For a common "brl languages" forum the blitzng domain sounds good to me... 


Regarding sphinx and the likes... I just am seeing how others build their doc-sites (github+jekyll) out of missing experience I cannot tell if this is already overkill or not.


Maybe @nitrologic will also jump in adding some comments here.

**Comment by nitrologic** [comment]
I will have a mirror up soon. To some degree I did lose the plot today, after being called a barking dog on monkey-x  I was finding it difficult to manage levels of hostility bubbling through my arteries.

**Comment by davecamp** [comment]
@MikeHart66
It wasn't me my friend, I *think* it was someone over there by the name of Qube.
And err yeah, that was some reaction this morning. No need to discuss that though. Let's move forward...

**Comment by HenriVi** [comment]
Hi,
some outlet for BMX-NG would be in place (and discussion about it) wether it be dedicated site or a channel like in the original bb site. I've registered in syntaxbomb just to stay connected.
I'm developing serious software with BMX (powered by Bruceys modules ) so having some userbase around it is always a good thing.

-Henri

**Comment by GWRon** [comment]
I assume the "chatters" (read "common room"-users) already concentrated on syntaxbomb. Nonetheless the "hardcore users" might still be convincable to use a new founded blitz-community-page which would also be there to keep the "products" alive. Many people were so used to BMax, B3D, ... that they also care for the presentation to the outside world (-> that "others" have chances to recognize the blitz-languages at least).

Dunno what happens at the monkey-x front - maybe they won't join a new community as they (in their forums) seem to think people at the blitz-boards disliked them so much.

I think we would have some "hardcore users" with high reputation in the boards who would join the forum which would become the official "bmx ng" one (including brucey's modules).


One big problem is: the more we wait, the more things will settle and the harder it will become to fetch some users (to keep "traction" in development).


Regarding forum I have something else to add: Modern forum software often has logins to let people login with facebook (or so). This might inrease userbase as registration hurdles are avoided.

**Comment by davecamp** [comment]
As was mentioned by GWRon, I have registered blitzng com. If you want it redirected to anywhere that is very easily arranged.

My 2 penny thoughts to throw into the mix are...
This could also be an opportunity to help the NG versions ( Max and 3D ) to get better recognition. I noticed that NG was getting more and more ( well deserved IMHO ) attention in the forums. Blitz3DNG was also starting to get an airing too. I feel the downside to both of these is that they both require building from source, plus they definitely need more noise ( read as marketing, :-) ). If stable release builds were made for both products ( are monthly builds for their respective targets too much? ) then they will attract so many more programmers hopefully from outside the Blitz communities.
I'm just thinking to use the opportunity not to resurrect what once was at the Blitz forums, but to move forward promoting and bringing the NG versions to the fore-front, whilst still allowing forum support for the legacy product users - there are a respectable amount of them and I don't mean in any way not to include them - I am one myself!

Anyway of course that requires an initial base station to work from.
Any thoughts/reactions on this idea?

**Comment by GWRon** [comment]
Monthly builds sound good - but I do not know a way to build the mac-builds on a linux server. 

I always hoped for a "build server" (stable + daily) but it seems as it needs eg. a little Mac Mini (located at "Bruce Mansion") which does a little bit work and uploads it after completition.

Regarding hosting: every advanced usage needs root access to the server - so a VPS or dedicated one is needed.

Brucey wanted a documentation thing - so all in all it needs:
- forum
- documentation service/script/software/solution
- some simple (static?) CMS to present "about/showcase/tutorials"
- optional: build server (VM for Mac _could_ do)
- ???

A vserver/rootserver does not cost that much:
https://www.netcup.de/vserver/vps.php
think with 4 eur/month you already have enough horse power to drive the whole thing - and if really needed. Build servers could get offloaded to user builds (if trusted).

Regarding marketing and other solutions: as this is then no longer "company driven" but "community driven" it would be up to us to do the "buzz creation". And this should not get discussed here - as this surely derails the whole thing "a bit" - maybe meanwhile create a new issue for it.

I also had another domain name in mind which I mailed to Bruce - so if he likes it, we also could use that (it is less cryptic than "blitzng" - which works too, of course!).


Regarding monkey: if anyone of you knows about "active monkey community maintenance", then monkey should become included too (maybe we could convince some of them to use bmxNG instead :-p).

**Comment by woollybah** [comment]
As we are all throwing ideas around, I've been working on a maven-type module packaging thing for BlitzMax, in which each individual module would be packaged separately and downloaded as required (into a local cache) for building.
Each module would know its dependencies. When building an app with a particular module, the system would fetch and compile any missing dependencies as required.
This would fix issues like having to download ALL of bah.mod, when you are perhaps only interested in say, bah.volumes. ;-)

Anyhoo, back to the important stuff...

I think using sphinx as a documentation site generator is a good way forward (sphinx builds static sites, see [emscripten.org](http://kripken.github.io/emscripten-site/) for a nice example).. I also believe it can be tweaked (i.e. write a plugin/extension for it) to process BlitzMax source in order to get at the bbdoc stuff - although the bbdoc in general is, sadly, pretty sparse.
In which case, I see a job to improve BlitzMax's documentation in general.
There are many user-made resources that could be pulled together to compliment the documentation, and create something that can actually help people to learn how to use it.
And of course, NG has one or two additional features that could do with some decent text to explain things...

I'm all up for a combined "NG" site, but I don't know anything about the current state of the other project, or its future potential.

As for BlitzMaxNG, I feel that the generics stuff is almost ready to be merged into master... yay! :-)

**Comment by HenriVi** [comment]
I do like the emscripten.org as a good example of showcasing a product and concentrating resources in an accessible way. It's important to offer sufficiently up-to-date ready made builds for people to try it out. This lowers the barrier for new users, and also the variables of debugging problems.
As for marketing, probably first step would be to open up a subforum / topic in where the existing userbase is. But of course all in due time.

-Henri

**Comment by Kerntrick** [comment]
A dedicated NG forum is really needed imo.   I use NG every day and would like to stay connected with other users.  I'll help anyway I can.

**Comment by GWRon** [comment]
A new blitzmax.org website emerged "halfly" - it just misses a forum (if there is one needed). For now it links to syntaxbomb.com, which is a great place to stay and for now there is not a big enough crowd to justify an individual forum.

close?
