### ISSUE TITLE
Latest Weekly-Build "docmods/makedocs" stalls forever.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#191]
Discord user "GW" reported that the module documentation building (done on an first-run of maxide) stalls forever:

I replicated it:
![image](https://github.com/user-attachments/assets/386c1b33-5a34-4980-a0c3-385b6d814cbc)

using older makedocs/docmod builds worked fine, so I ruled out that some module-source changes made it hang.
I then rebuilt both binaries with the latest weeklies bcc (so maxide -> open docmods.bmx etc) and replaced both binaries.

These binaries allowed to build the module documentation.

So what is the difference? I compiled them from within Windows 10, the weekly build is done via cross-compile within docker.

Can you (@woollybah ) replicate the issue? And why did it work "before"? is the cross-compiler-toolchain version (gcc etc) different now?

**Comment by MrMisanthrope** [comment]
Still fails in **BlitzMax_linux_x64_0.146.3.58.202411170215**

**Comment by GWRon** [comment]
I already reported that after the fixing commit last sunday. It should now work under Windows but somehow it now fails for Linux.

Simply rebuilding docmods with the provided bcc/bmk/maxide should make it work
