### ISSUE TITLE
Build modules fails in glue.cpp

### ISSUE THREAD

**Issue by MrMisanthrope** [bmx-ng/bmx-ng#197]
When building all modules, compilation fails in glue.cpp @ line 385

**To Reproduce**
Choose build modules from Program menu.

**Expected behavior**
Error free build of all modules.

**Screenshots**
![Screenshot_2024-11-18_14-21-33](https://github.com/user-attachments/assets/bfca4391-3110-4043-bab0-bfca410d5af9)
![Screenshot_2024-11-18_14-43-13](https://github.com/user-attachments/assets/6b9411ad-545f-4945-99b2-a106b1bd82c1)

**Version information (please complete the following information):**
 - OS: Linux (Debian 11/Bullseye 64bit)
 - bcc[ng] Release Version 0.146
 - bmk 3.58 mt-linux-x64
 - MaxIDE 1.56 [ng] (x64)

**Comment by GWRon** [comment]
I provided a PR to fix it - some days ago @woollybah added a new `bb_thread_t` to get rid of some compiler warnings newer GCCs produce ... they do not like the casts we did before.
