### ISSUE TITLE
Cannot build bmk.bmx

### ISSUE THREAD

**Issue by luk22** [bmx-ng/bmx-ng#23]
Hello,

I downloaded latest bmx-ng release for windows 'BlitzMax Win32 v0.87.3.16' and all latest mods including bah.box2d

I can't build bmk.bmx (I get compile errors)
I can't build blitz.mod (I get compile errors)

Using out-of-the box builds I can't compile any box2d example (I get compile errors)

Please help. I have very advanced project in Std Blitzmax (it works like a charm) which I'm making for over 3 years. 
Now I need badly mojo2 shaders.

This is my game website: www.hiddendeepgame.com

Thank you in advance

**Comment by luk22** [comment]
Sorry Box2D works finally (my mistake)

**Comment by GWRon** [comment]
Download most current BMK...compile it.

Use the new BMK to compile the most current BCC and with that you should be able to compile all modules ...except currently broken ones.

**Comment by luk22** [comment]
I did what you said and:
Compile Error: Variable for 'Var' parameter is not of matching type
Build Error: failed to compile (-1) C:/BlitzMaxNG/src/bmk/bmk_bank.bmx

**Comment by GWRon** [comment]
If unsure: compile BMK and BCC(ng) with vanilla Blitzmax.

I am not on my computer now but I thought it was possible to compile both with NG toolchain too.

With NGs MaxIDE you could tick on a menu-checkbox to ignore warnings and the likes (available with more current BMK files).

**Comment by luk22** [comment]
In vanilla:
Compiling:bmk_config.bmx
flat assembler  version 1.69.14  (1048575 kilobytes memory)
4 passes, 25737 bytes.
Compiling:bmk_cores_win32.c
C:/BlitzMax/src/bmk/bmk_cores_win32.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #include "windows.h"
 ^
C:/BlitzMax/src/bmk/bmk_cores_win32.c:1:0: error: CPU you selected does not support x86-64 instruction set
Build Error: failed to compile C:/BlitzMax/src/bmk/bmk_cores_win32.c
Process complete

**Comment by luk22** [comment]
I think something is wrong with latest bmk, because out-of-the box bmk compiles

**Comment by GWRon** [comment]
So your mingw is 64bit only?

Using tdm mingw should work.

**Comment by luk22** [comment]
I used mingw bundled with bmx-ng. gcc.exe (tdm64-1) 5.1.0

**Comment by luk22** [comment]
Ok, I switched to old MinGW. There is some progress, bmk compiled

**Comment by luk22** [comment]
Almost there. There was many errors in various modules but I managed to fix them (not sure if I did it correctly). BTW - is NG still maintained? (I sooo much don't want to go to that Unity thing....)

**Comment by GWRon** [comment]
Yes. Think Brucey will show activity in not much time. He is still busy with life atm.

**Comment by luk22** [comment]
Good to hear. One question: you said "Use the new BMK to compile the most current BCC" so after compiling bmk I should put bmk.exe to Vanilla bin directory and then compile bcc?

**Comment by GWRon** [comment]
Nope, i was trying to explain how to update to the latest revisions of NG...consisting of BCC, BMK (and the updated .bmk files in that directory) and updated modules (brl and pub.mod)

While new versions might introduce bugs, they might have solved some which you fight now.

**Comment by luk22** [comment]
So I should put bmk.exe compiled in Vanilla to NG-bin and then compile bcc (from NG-IDE)?

**Comment by GWRon** [comment]
Bcc and bmk ng should both compile with vanilla...or maybe with your v0.87


After compilation you put them to your ng/bin...
Also copy new brl.mod and pub.mod to ng/mod

Afterwards you should be able to compile more of the modules in ng/mods ...or not, as they might not be updated for NG.

Am 12. Oktober 2017 23:07:16 MESZ, schrieb luk22 <notifications@github.com>:

**Comment by luk22** [comment]
Thanks.

**Comment by luk22** [comment]
Re: [bmx-ng/bmx-ng] Cannot build bmk.bmx (#23)


BTW. Do you know if it is possible to port mky.mojo2 to Vanilla Blitzmax (I will pay :) ?

-- 
Pozdrawiam,
Łukasz Kałuski




Witaj Ronny! Dnia 2017-10-12, 23:12, napisałeś(aś):





Bcc and bmk ng should both compile with vanilla...or maybe with your v0.87


After compilation you put them to your ng/bin...
Also copy new brl.mod and pub.mod to ng/mod

Afterwards you should be able to compile more of the modules in ng/mods ...or not, as they might not be updated for NG.

Am 12. Oktober 2017 23:07:16 MESZ, schrieb luk22 <notifications@github.com>:

**Comment by GWRon** [comment]
It should not be possible without many/big chances. Reason is the usage of "interfaces" which is not directly possible with vanilla.

**Comment by woollybah** [comment]
Sorry. A bit late to the party. mojo2 may already work with the legacy compiler.

Anyhoo, there's a new Windows release of NG for Windows which includes mojo2 if you want to give that a try?

**Comment by GWRon** [comment]
mojo2.mod seems to compile with vanilla, but examples are using `implements interface` so this wont work without a (big) bit rewriting.
