### ISSUE TITLE
glmax2d full screen problems (even in Vanilla)

### ISSUE THREAD

**Issue by luk22** [bmx-ng/bmx-ng#24]
I've got Win7 64bit + Asus GeForce 1060 6GB. My game uses 1280x720 res. In windowed mode all is OK, but in fullscreen mode there are randomly missing images on random frames (once per 2-3 seconds). I checked it in Vanilla also and got the same results.

**Comment by GWRon** [comment]
Even in vanilla...

...so it is probably an error/flaw in your code.


Try to cut it down to a small piece of still-not-working code and post it here so we could have a look.

**Comment by luk22** [comment]
But on DirectX it works like it should. Also on OpenGL in windowed mode it also works. Do you have any suggestion what kind of mistake it could be? Where should I look (It's big project so it's not that easy)

**Comment by luk22** [comment]
I tested it on my laptop and everything is OK. Maybe newest GeForces cards do not support old opengl well

**Comment by GWRon** [comment]
Still valid?

**Comment by GWRon** [comment]
Still valid? ... bump. ... close "invalid" ?

**Comment by luk22** [comment]
I cannot check it right now because I'm now using some DX-only libraries and cann't run it on OpenGL. I'll try to run some older version and check it

**Comment by woollybah** [comment]
Other than the way the GL context is initialised for creation in a window, or as fullscreen, there's nothing different about how BlitzMax renders everything.
It could be a driver issue.

It may also be worth trying the SDL backend (with sdl.gl2sdlmax2d, which draws using shaders), if that's feasible.
