### ISSUE TITLE
Unable to build on MacOS 10.14+Xcode 10 (LLVM 10.0.0)

### ISSUE THREAD

**Issue by dastho71** [bmx-ng/bmx-ng#36]
On MacOS 10.14 with XCode 10 (LLVM 10.0.0), libstdc++ is deprecated and no longer found by clang. Every build ends with:

_clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)_

The warning is shown since MacOS 10.12+, but was ignored and the builds where running anyway.

bcc[ng| Version: 0.94
bmk Version: 3.24
clang Version: 1000.11.45.2
GCC Version: 4.2.1
G++ Version: 4.2.1

**Comment by woollybah** [comment]
As a quick fix, you can use these lines in make.bmk, in the `@define default_cc_opts` section at around line 420...
```
			globals.SetOption("cc_opts", "osversion", "-mmacosx-version-min=10.9")
			globals.SetOption("ld_opts", "osversion", "-mmacosx-version-min=10.9")
			globals.SetOption("ld_opts", "stdlib", "-stdlib=libc++")
```

**Comment by dastho71** [comment]
Thank you Brucey, that fixed the issue.
