### ISSUE TITLE
BlitzMax Linux.x64 v0.98.3.27 - Rebuild All Modules Fails

### ISSUE THREAD

**Issue by Sledgenet** [bmx-ng/bmx-ng#38]
IDE Output:
```
/home/[ME]/Downloads/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/audio/esd/SDL_esdaudio.c:31:10: fatal error: esd.h: No such file or directory
 #include <esd.h>
          ^~~~~~~
compilation terminated.
Build Error: failed to compile (256) /home/[ME]/Downloads/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/audio/esd/SDL_esdaudio.c
Process complete
```
This is under Ubuntu 18.04.01

**Comment by GWRon** [comment]
You might try to install `libesd0-dev`

Sudo apt-get install libesd0-dev

**Comment by Sledgenet** [comment]
Aha, so it is `libesd0-dev` that I need -- thanks! Looks it is deprecated, updated installation instructions can be found here: https://askubuntu.com/a/1082739

_However_... that merely punts the problem a little further down the field:
```
In file included from /home/[ME]/Downloads/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/audio/nas/SDL_nasaudio.c:34:0:
/home/[ME]/Downloads/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/audio/nas/SDL_nasaudio.h:29:10: fatal error: audio/audiolib.h: No such file or directory
 #include <audio/audiolib.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
Likely this is just a chain-reaction of broken-ness so don't sweat it. I check NG probably once or twice a year to see if it is "just works" territory yet so I got my answer :smiley:

**Comment by GWRon** [comment]
I am not on 18.xx yet...and for me it runs without further issues.

Think Brucey needs to check it out in a 18.xx VM. Maybe SDL has some more instructions for the requirements with these audio backends.

**Comment by GWRon** [comment]
If you did not update the modules yet...maybe update brl.mod pub.mod sdl.mod ... from their repos. 

So an updated SDL mod might already solve your issue

**Comment by Sledgenet** [comment]
Appreciate the suggestion -- getting the same issue with the latest versions of those mods pulled unfortunately. Ubuntu Software Update ran an upgrade literally a couple of days ago so I think I've just picked the worst time possible to give this a go.

**Comment by GWRon** [comment]
Tried to replicate it:

- downloaded release
- error during extraction of the download (a file within sdl.mod was not found), manually unpacked everything else (drag n drop out of the archive manager), downloaded sdl.mod and placed it into the mod dir
- had to install "libwebkitgtk-3.0.0" too to get MaxIDE running
- error in sdl.mod/sdl.mod/SDL/src/audio/esd/SDL_esdaudio.c - "esd.h" not found.

So seem that audio backend needs to get disabled ?!

**Comment by GWRon** [comment]
For now you might continue your blitzmax-exploration by opening up "sdl.mod/sdl.mod/linux_source.bmx", scroll some lines down, and comment out the line importing the esd file:

replace:
```BlitzMax
?linux And Not raspberrypi
Import "SDL/src/audio/esd/SDL_esdaudio.c"
Import "SDL/src/audio/pulseaudio/SDL_pulseaudio.c"
```
with
```BlitzMax
?linux And Not raspberrypi
'Import "SDL/src/audio/esd/SDL_esdaudio.c"
Import "SDL/src/audio/pulseaudio/SDL_pulseaudio.c"
```

also replace two lines in each sdl.mod/sdl.mod/include/linuxx64/SDL_config.h and ../linuxx86/SDL_config.h:
```C
#define SDL_AUDIO_DRIVER_ESD 1
#define SDL_AUDIO_DRIVER_ESD_DYNAMIC "libesd.so.0"
```
with:
```C
#define SDL_AUDIO_DRIVER_ESD 0
#define SDL_AUDIO_DRIVER_ESD_DYNAMIC
```
(without this replacement you end up with some undefined references to "ESD_BOOTSTRAP")


The SDL dynamically links to backends, so if it (ESD, PulseAudio, ...) was not available, it uses another one. Means it should run without ESD too (on a client's computer).


Make sure to completely recompile the SDL.mod modules (not "quick") as you else end up with undefined references (it mixes cached precompilates with the new, esd-free, ones).

**Comment by GWRon** [comment]
@woollybah 
SDL should be "reconfigured" to not use ESD for Ubuntu 18.04+ - it also seems that it is kind of deprecated (PulseAudio 2.0 drops support for ESounD, development of the lib seems ...dead). So it might not be a missed backend by the default BlitzMax-target-audience.

**Comment by GWRon** [comment]
Brucey updated sdl.mod ...please give it a try and close the issue if the commit solves your problem.

**Comment by Sledgenet** [comment]
Thought I'd swing by for another crack at it. Latest NG repo with latest pub.mod, brl.mod and sdl.mod:
```
In file included from .../BlitzMaxNG/mod/sdl.mod/sdl.mod/SDL/src/audio/nas/SDL_nasaudio.c:34:0:
.../BlitzMaxNG/mod/sdl.mod/sdl.mod/SDL/src/audio/nas/SDL_nasaudio.h:29:10: fatal error: audio/audiolib.h: No such file or directory
```
It is different at least :D

**Comment by GWRon** [comment]
Did you install the modules listed in the bmx-ng/sdl.mod readme.md file/project start page:

`libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev libudev-dev`

?

**Comment by Sledgenet** [comment]
I was missing libaudio-dev from that list -- everything building now. Thanks GWRon, much appreciated.
