### ISSUE TITLE
Assertions aren't evaluated in debug build

### ISSUE THREAD

**Issue by FWeinb** [bmx-ng/bmx-ng#4]
I just tried the latest version and noticed that assertions aren't evaluated in any way. 

Here is a reduced test case:
```bmx
SuperStrict
Framework BRL.System

Function test(value:Int)
  Assert value > 0, "This is not possible"
  DebugLog "Function run"
End Function

Try
   test(-1)
   DebugLog "This is wrong!"
Catch e:Object
   DebugLog e.toString()
End Try
```
With the original bcc/bmk in debug build this evaluated to:
```
DebugLog:This is not possible

Process complete
``` 

In bmx-ng the assertion is ignored in a debug build and this is evaluated to:
```
DebugLog:Function run
DebugLog:This is wrong!
```

**Comment by woollybah** [comment]
This issue was moved to bmx-ng/bcc#121
