### ISSUE TITLE
BMAXPATH/MinGW path problem

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/bmx-ng#40]
This sort-of relates to [Fix for invalid BMXPATH](https://github.com/bmx-ng/bmx-ng/issues/32), though MaxIDE starts up fine.

There seems to be a problem in the latest Win32 release, where I'm seeing lots of different build errors and/or crashes, depending on build/arch options selected.\*

I _think_ it might relate to all the references to `BlitzMaxPath() + "/MinGW32"`, though -- there are many -- as my 'Build Modules' and 'Rebuild Modules' options are permanently greyed-out. My BMAXPATH is correctly set.

eg. [this line](https://github.com/bmx-ng/maxide/blob/7b175bc2556e77a6465ee0dbf749045a97155259/maxide.bmx#L6719).

I can't immediately see anything that modifies this MinGW string -- from the example line above...

```
?Win32		
		Local mingw$=BlitzMaxPath() + "/MinGW32"
		If Not FileType(mingw) Then
```

... but the Win32 folder structure now includes _two_ versions of the MinGW32 path, /MinGW32x64 and /MinGW32x86, with plain /MinGW32 being non-existent:

```
 Directory of D:\DevTools\Blitz\BlitzMaxNG

07/11/2018  01:07    <DIR>          .
07/11/2018  01:07    <DIR>          ..
07/11/2018  00:52    <DIR>          bin
07/11/2018  01:24    <DIR>          cfg
07/11/2018  01:07    <DIR>          doc
07/11/2018  01:07    <DIR>          docs
07/11/2018  00:52         2,186,573 MaxIDE.exe
07/11/2018  00:49    <DIR>          MinGW32x64
07/11/2018  00:50    <DIR>          MinGW32x86
07/11/2018  00:49    <DIR>          mod
07/11/2018  00:49    <DIR>          src
07/11/2018  23:53    <DIR>          tmp

```
\* When I get build errors, it's along the lines of this sort of thing -- missing GC stuff:

```
[ 98%] Compiling:drcs.bmx.gui.release.win32.x64.c
[100%] Linking:drcs.exe
D:/Documents/Development/Sources/BlitzMax Sources/Dirt Rally Config Switcher/.bmx/drcs.bmx.gui.release.win32.x64.o:drcs.bmx.gui.release.win32.x64.c:(.text+0x3d6): undefined reference to `GC_add_roots'
D:\DevTools\Blitz\BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.release.win32.x64.a(win32maxguiex.bmx.release.win32.x64.o):win32maxguiex.bmx.release.win32.x64.c:(.text+0xa2a8): undefined reference to `bbExThrow'
D:\DevTools\Blitz\BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.release.win32.x64.a(win32maxguiex.bmx.release.win32.x64.o):win32maxguiex.bmx.release.win32.x64.c:(.text+0xa528): undefined reference to `bbExThrow'
D:\DevTools\Blitz

```

**Comment by woollybah** [comment]
brl.maxutil now has a MinGWPath() function (based on one from bmk) which maxide is now using.
The About dialog should now always display this information correctly.
