### ISSUE TITLE
Latest Linux-Release download archive broken

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#48]
The downloadable archive of the latest Linux release:
https://github.com/bmx-ng/bmx-ng/releases/tag/v0.98.3.27.linux.x64

is broken/corrupt. It cannot get successfully/completely extracted. Either re-upload or fix with a new release next time (if it is already on horizon...)

**Comment by woollybah** [comment]
There's a new release.
This works fine for me.
