### ISSUE TITLE
Operator Overload Examples

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bmx-ng#51]
Find a way to create examples for operator overloads.

It may need some mapping of a specific name to the operator, since we can assume that most of the characters are not valid for file names.

bcc already translates operators into munged names. We may be able to use this mapping : 

https://github.com/bmx-ng/bcc/blob/ebdf17914fcb46687ffe3d46b421024324051382/translator.bmx#L398

**Comment by GWRon** [comment]
As functions are allowed to get named "myfunc_mul()" I think it is generally not the best idea of the munging function in BCC..
Regardless of this: as a dot is not allowed in function names but in file names, this might be utilized somehow (functionname.operator.md).
Next to dots there is also the "dash/minus" ( - ) which could be used across various file systems ...if you already used the dot differently.
