### ISSUE TITLE
How to ensure that a method is overriding a parent's one?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#56]
I have a type `A` which defines a method `mth`.
Now I have a type `B extends A` and I want to ensure that a `mth` I write there is overriding the one of `A`.

Assume someone changes the definition of `A.mth` to accept other params. In vanilla you would now receive an error as things do no longer fit together (A.mth vs B.mth definitions). In NG we have overloading which means now both methods coexist.

Is there something like `final` but with another restriction - a final "method definition" or "no overload" ?

**Comment by HurryStarfish** [comment]
There is nothing of the sort currently, but that's a good point. In vanilla it was fairly straightforward to get overriding right. But in NG, with overloading and interfaces added to the language, it's easier to make mistakes. C# has an `override` keyword to deal with this, Java has an `@Override` annotation. It would be useful to add the same to BlitzMax:

```
Type T1
	Method M(s:Object)
	End Method
End Type

Type T2 Extends T1
	Method M(o:Object) Override ' <- everything is alright
	End Method
End Type

Type T3 Extends T1
	Method M(o:String) Override ' <- compile error, because the signatures don't match
	End Method
End Type

Type T4 Extends T1
	Method M(o:Object) ' <- compile error or warning, because "Override" is missing
	End Method         '    (with a switch in MaxIDE for legacy compatibility, similarly to "Overload warnings")
End Type
```

**Comment by woollybah** [comment]
I think an `Override` property would be a good addition.

**Comment by GWRon** [comment]
As you wrote you would not call a property "Flags" as you named some variables already that way...

If it can only get used in function definitions, I do not see an issue appending such stuff if it had common names.

**Comment by HurryStarfish** [comment]
> So a warning option would be because we want to enforce use of `Override` for any method that overrides another?

Yes, to make sure `Override` can't be forgotten and is used consistently. It can then prevent the opposite mistake: accidentally creating an override when the intention was to create sn overload or an entirely new method.

**Comment by GWRon** [comment]
This would by the way mean a lot of modules need to get updates...as they extend from others.

**Comment by GWRon** [comment]
I cannot imagine the impact...but what about requiring `override` only for `superstrict` and not `strict`.

**Comment by HurryStarfish** [comment]
True... considering that it should certainly be a warning (rather than an error) and be set to "off" by default. Strict/SuperStrict on the other hand shouldn't really matter, since it only affects method return types whereas overriding depends on the parameter types.

**Comment by GWRon** [comment]
`override` needs to ensure that it fails if it does not override a function/method. In other words: `override` should fail if the original function does no longer exist or now uses different parameters.

**Comment by HurryStarfish** [comment]
> `override` needs to ensure that it fails if it does not override a function/method. In other words: `override` should fail if the original function does no longer exist or now uses different parameters.

Yes. To clarify, what I am saying is:

- having `Override` on a method that is *not* actually an override should be an **error** (always)
- *not* having `Override` on a method that *is* actually an override should be a **warning** (which can be disabled with an option in MaxIDE, and is disabled by default for backwards compatibility)

**Comment by woollybah** [comment]
I've pushed updates to bcc and bmk.
I think I've covered all of the variations, but it's possible I missed something, so feel free to find faults :-)

I'm holding off updating brl until the compiler changes have been live for a while.

**Comment by GWRon** [comment]
Is there a valid reason to disallow "property names" like `Final Abstract Override...` for variable names? 

A function signature has a specific structure...you cannot mix up `final:int` with the property.
Also `method final:int() final` could be interpreted correctly.

What am I missing?

**Comment by HurryStarfish** [comment]
What you're suggesting is making them what's called "contextual keywords".
This would be possible, but without an IDE that is actually smart enough to recognize this, it's probably of questionable use. Even if you could use `Abstract` etc. as identifiers, MaxIDE would still capitalize and highlight them as keywords. (I do wish we had an IDE integrated with the compiler that was capable of autocompletion, showing errors in realtime etc....)
Related to bmx-ng/bcc/issues/383.

(Additional random thought:
The disadvantage of "real" keywords (not anymore being allowed as identifiers) could arguably also be an advantage - once established, a keyword can be reused for more features  in the future without breaking backwards compatibility again. Granted, this hasn't happened much so far and depends on the keyword... I can imagine words like `Final` or `ReadOnly` being more useful for future features than, say, `Override` or whatever we're going to use for bitflag enums...)

**Comment by GWRon** [comment]
IDE is another topic...and best chances are surely to create a language plugin for one of the major IDEs around... Intellij, atom, visual studio code... But this is for another issue and discussion.


@ highlighting
Just mark them as a secondary keyword which does not get autocapitalized or highlighted.
But yay, MaxIDE is for now a visual issue.

Is there any compiler wise issue prohibiting "contextual keywords"?

**Comment by HurryStarfish** [comment]
That would mean not having them highlighted anymore in MaxIDE at all.
But no, compiler-wise there should be no issue. See bmx-ng/bcc/issues/383: it appears `Final` **is** in fact already a contextual keyword in NG, albeit (I assume) accidentally.
