### ISSUE TITLE
 encapsulation ??

### ISSUE THREAD

**Issue by llYuell** [bmx-ng/bmx-ng#61]
Hi, the encapsulation didn't work properly. 

```

Type TBox

    Private n:byte = 100

end Type 

local box:TBox = new TBox

box.n = 200
print box.n  ' Print 200, variable type private. :(
```

**Comment by woollybah** [comment]
In a local file, access to private/protected members is allowed.
However, if you `Import` a file with limited access members, the standard encapsulation rules apply, and any Private members will not be visible. Protected members can be accessed via subclasses.

This enables you to create local dependent types that have access to members that you maybe wouldn't want to expose externally.

**Comment by HurryStarfish** [comment]
```
Type TBox

    Private n:byte = 100

end Type 
```
This doesn't compile in the first place, it's missing a `Global`, `Field` or `Const`. But seeing how you formatted it, keep in mind that when you write `Private`, it does not just apply to the next declaration (like in Java for example), but to everything that comes after it (like in C++). For that reason, I would recommend writing it on its own line.
