### ISSUE TITLE
Fullscreen mouse oddity

### ISSUE THREAD

**Issue by wombatswaffles** [bmx-ng/bmx-ng#66]
Hi,

I'm running on macOS Mojave.

When running the following, MouseY() seems to be inverted.

```
Graphics 640, 480, 32
Repeat
	Cls
	DrawText(String(MouseX()) + ", " + String(MouseY()), 32, 32)
	DrawRect(MouseX(), MouseY(), 64, 64)
	Flip
Until KeyHit(KEY_ESCAPE)
```

**Comment by GWRon** [comment]
Duplicate of https://github.com/bmx-ng/brl.mod/issues/79

**Comment by wombatswaffles** [comment]
Oops. Sorry!

**Comment by GWRon** [comment]
No need to excuse. Just wanted to help "organizing" the issues - and to redirect your awareness to the existing one (as it contained a temporary solution).

**Comment by wombatswaffles** [comment]
Thank you. Now I have a [new issue.](https://github.com/bmx-ng/brl.mod/issues/110)
