### ISSUE TITLE
How to avoid accidentally compilation of non-main-files?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#67]
If you have a "myproject.bmx" which imports other files - eg "main.bmx" and hit "compile" accidentally while "main.bmx" is active (in other words: you compile main.bmx as application) you run into trouble.
NG now compiles all that little stuff into main.bmx and once you want to (quick) compile "myproject.bmx" again you will see a lot errors about undefined references and the likes.

The only way to get it work again - is to do a full recompile of all the sources (which in bigger projects take a while).

So ... what could we do? As stated multiple times already we could extend the "comments" to guide BMK: `'@BMK do this and that`

In our case we could have something like this:
```BlitzMax
'@BMK compileAsApplication=false
'or
'@BMK sourcetype=library
```

What do you think - how do you circumvent this issue (which is only an NG one, not a vanilla one)

**Comment by HurryStarfish** [comment]
You can "lock" the main file in the Program menu in MaxIDE.
Long-term though, some sort of project/solution system would be useful to deal with this kind of thing.

**Comment by GWRon** [comment]
MaxIDE is an "external" solution. And I do not use MaxIDE except for debugging (I think Geany is way more convenient for me).

A Project/Solution system should be optional (to still allow rapid prototyping without setting up project files first). BMK must then made aware of "file x" belonging to a project - which seems to say "one project per directory".

**Comment by woollybah** [comment]
I don't think there is currently anything that bmk/bcc should be involved in from a project level.

**Comment by GWRon** [comment]
I don't think so. It is bcc's fault that trouble arises if you compile a "imported file" as application.
If bcc wasn't storing stuff in .i2 files (and others) the way it does now, then there would not be issues.

So I think it would be legit to somehow alter that behaviour...or to disable certain functionality.

These files btw also contain absolute paths ... Potential issue for projects on USB-Sticks or when moving them to other directories.
