### ISSUE TITLE
Events borked when doing a Mac "console" build

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#68]
If you do not build a GUI application for your graphics application on a mac it means it opens a terminal (to prompt your prints etc) and then opens up a graphical window.

While mouse movement seems to work fine, mouse clicks are no longer properly recognized (sometimes you need to move the mouse while clicking - or you are not allowed to move while clicking).

Apparently it is borked up the same with vanilla BlitzMax - so it might not be SDL but something else ?!

**Comment by woollybah** [comment]
If you want a non-console application in macOS, you need to choose the "gui" option when building your application. This enables the correct functionality - like, for example, window and events interaction.

**Comment by GWRon** [comment]
Hmm a pity as this works fine on Windows etc.

Is there a way for a module/sourcefile to registrate how it is build? So it could throw something on a mac if build in console mode?
So the graphic stuff could somehow inform that this won't work.

Maybe add a new conditional?

**Comment by woollybah** [comment]
On Windows you should be doing a GUI build also, for windowed applications - otherwise a console window opens when the app is started.

As has always been the case, if you want to build "gui" apps in BlitzMax, you should select the "gui" build option.

**Comment by GWRon** [comment]
The console window is desired for dev purposes as it contains a live view to debug messages (and print).

Better than having this stuff drawn over in a low res graphics window.

**Comment by woollybah** [comment]
Well, I'm just saying, that it has always been the case that for a GUI based application, you need to select the "gui" build option. That's not going to change.

macOS console apps and macOS gui apps are entirely different things. A console app is a single binary. A GUI app is a folder with lots of other stuff inside it.

**Comment by GWRon** [comment]
Recognized that already yet I preferred to have an open console next to the graphics window.

Dunno if it is "easily" possible to spawn a new terminal/console window from within the "graphics window" (even if not initialized yet) and to redirect output (print) to this window?

That way we could build GUI and still output to "somewhere" (without relying on having it open in MaxIDE or starting it from terminal)

**Comment by DivineDominion** [comment]
If `NSLog` or one of the various new `os_log` functions on Mac were used, you could redirect DebugLog output to the macOS Console. Not sure what print could do different in these cases.
