### ISSUE TITLE
Mac: "Duplicate Large Block deallocation" error

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#73]
Just tried to compile the "streamed audio with Freeaudio"-Variant of GenusPrime on my mac and right on start I got this error: `Duplicate Large Block deallocation`.

Compiled it with Debug enabled (30 minutes for debug module compilation ... pheew old core duo):
(Message box "forced close").
MaxIDE:
```
[16:43:19] LOAD      | TASSETS.INITIALIZE: Loaded assets
GenusPrime.debug(2053,0x7fff7c91a300) malloc: *** error for object 0x10da1f020: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```
Hmm ... how to debug this?

**Comment by GWRon** [comment]
The error is happening in my "freeaudio" sound manager + the corresponding C file.

the error states I am freeing something which I shouldn't but I do not see any freeing/deletion in the C file:
https://github.com/GWRon/Dig/blob/master/base.sfx.soundmanager.freeaudio.c

The test application plays a sample multiple times and crashes after crossfading and while playing the third time. Adding a GCCollect to the loop instantly makes it crash (but without the `Duplicate Large Block deallocation` error message).

**Comment by woollybah** [comment]
You can put a breakpoint on `malloc_error_break` like it says, and it will stop when you get the error. Then you can see exactly what you are freeing twice.

**Comment by GWRon** [comment]
And how do I do that - I "speak" BlitzMax-ish.

**Comment by woollybah** [comment]
Well, you may need to run it in Mac's gdb equivalent - lldb?
I think the commands are similar in there. so you may be able to do something like `b malloc_error_break` before you run it.

**Comment by GWRon** [comment]
Ahhh yes, that does indeed bring up something.

**Comment by GWRon** [comment]
JFYI: I use `CreateStaticAudioSample(Byte Ptr(buffer), GetBufferLength(), freq, format)` so it might create something which the default `TAudioSample` does handle improperly?!

the interesting part is: `CreateStaticAudioSample` defines the property `capacity:int = -1`. Then memfree is only called when capacity is > 0:
```BlitzMax
	Method Delete()
		If capacity>=0 MemFree samples
	End Method
```

**Comment by woollybah** [comment]
Well, if your code is up-to-date `capacity` should be a `Long`. In which case it won't try to free static data.

**Comment by GWRon** [comment]
Ahh, seems the mac missed some module updates then - but why is it happening for "int" then ? -1 is -1 or not?

**Comment by woollybah** [comment]
Capacity was Size_t which is unsigned, and so was a bug.

**Comment by GWRon** [comment]
Ah well, that ... explains it. Will update and ... let the old machine recompile all this stuff. Man I thought with 25th of march I am pretty up to date ("never touch a running system" - especially during competition-time)

**Comment by woollybah** [comment]
Indeed :-)

**Comment by GWRon** [comment]
Now see why I was confuse: Linux box is on an older brl.mod (with `capacity:int`) while the mac (which I use via VNC - so a bit sluggish and keyboard mapping broken) was on a newer version - with `size_T`. All these little differences.

Will close "invalid" if it works. Thanks for your help.

**Comment by GWRon** [comment]
Invalid.
(I said the machine takes a while - and I only compiled the release version ;))
