### ISSUE TITLE
Mac: Building i386 with NG

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#74]
I tried to compile an i386 binary for Mac but it failed with a linker error with the i386. Tried to compile it again and now the error is:
```
dyld: Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Users/ronnymac/GenusPrime/GenusPrime.app/Contents/MacOS/GenusPrime
  Reason: image not found
```
Do I have to install additional stuff to compile for i386 (with xCode - as the vanilla blitzmax builds successfully)?

**Comment by woollybah** [comment]
Metal is not available on 32-bit apps, and something (SDL?) may be importing a framework for it.

Also, after Mojave, 32-bit's days are decidedly numbered...

**Comment by GWRon** [comment]
No longer needed.
