### ISSUE TITLE
Documentation for "alias" command

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#79]
For what is the "alias" exactly - and how to use it? Cannot find it in the documentation (maybe it is there already)?

**Comment by dmaz** [comment]
wasn't that removed long ago?

**Comment by HurryStarfish** [comment]
It has always been a reserved keyword even in vanilla BlitzMax, but as far as I know, was never actually used for anything. The idea might have been to eventually use it for some typedef-like functionality.

While I am not in favour of adding typedefs to NG in the forseeable future (unlike in C, we don't need them for portability, and they have a high potential for confusion), imo it keeping the keyword for the time being doesn't hurt either. Maybe it'll be useful for something in the future :)

**Comment by woollybah** [comment]
Yes, consider it reserved for future use.
