### ISSUE TITLE
Add new scripting language - js ?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#80]
Some people might not like Lua - or maybe it is not available on all platforms. Yes it is mighty but ...sometimes more mighty than needed (think of the modules). Also it has some security flaws (if you use the basic maxlua implementation) as a script can import modules and bypass limitations of your application.

Or in other words: github just suggested me some projects with one of them was "Dukglue" - a c++ wrapper for "Duktape" - a lightweight Javascript implementation in C:
https://duktape.org
which also links to alternatives like:
http://jerryscript.net

Both should at the end allow for a similar thing like `Brl.MaxLua` (so you can pass your stuff to jscript and run it there). Maybe the footprint is lower than with Lua? Maybe the language is more known/used for others - or maybe Brucey just enjoys wrapping libraries ;-)

I understand that Lua is already a scripting language wrapped for BlitzMax so I would be fine if there is no interest in it but as said where are maybe some benefits from having another scripting language.

See this issue as point for discussion, not as encouragement to wrap such a library. Just did not want to let the github-project-suggestion go unseen ;-)

**Comment by woollybah** [comment]
I don't think there is much need for another scripting addition.
And the work involved to get one integrated is quite high.

**Comment by GWRon** [comment]
Yes it is nothing we should do "now".

Lua is nice but as soon as you have complex conditions you will see how it blows up the code as you cannot exit loops or return in them etc. as the interpreter cannot do "look ahead" (performance reasons).

**Comment by llYuell** [comment]
I think there should be an update from 5.1 lua to 5.3.

**Comment by GWRon** [comment]
check bmx-ng/pub.mod#19
