### ISSUE TITLE
Brl-Threads vs C-Threads: hickups in BlitzMax App?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmx-ng#85]
I gave a dev-build of my game TVTower to a user requesting it... and he blamed that the game:
- crashes ~20 times per hour (with an EAV)
- has hickups while moving the mouse
- has stuttering sound

The sound bug was what raised my attention - as I included my streamed audio code (instead of maxmod2.mod/rtAudio.mod).
My tests lead to "delays" when using GL2SDL as driver (will create another issue for it) but the user reported hickups with OpenGL and GL2SDL too.
Sound stuttering was only replicateable for some milliseconds - and only in a 2-core-VM of XP 64Bit. On a real Windows 10 I did not experience issues. Also on my linux installations it runs flawless (at least in my tests...).

As C code I use this:
```C
#include <unistd.h>
#include <stddef.h> //definition of NULL

//forward declaration
int __startThread();
void __onAppExit();


//global vars
int threadID;
int updateStreamsEnabled = -1; //-1 = auto activate on registering a callback
int updateInterval = 500; //in ms


//definition and variable for callback
typedef int (*intCallback)(void);
intCallback updateStreamManagerCallback;


//register cleanup function
//this is called when the calling programme exits
atexit( __onAppExit );



// === FUNCTIONS ===

void __onAppExit() {
	stopThread();
}



int stopThread() {
	updateStreamsEnabled = 0;

	return 1;
}



int startThread(){
	updateStreamsEnabled = 1;

	return __startThread();
};



int RegisterUpdateStreamManagerCallback ( intCallback callback ) {
	updateStreamManagerCallback = callback;
	if (updateStreamsEnabled == -1)
		startThread();
		
	return 1;
}



void *updateStreamManager(void *v) {
	while(updateStreamsEnabled == 1) {
		//call the blitzmax function which updates the streams buffers
		if(updateStreamManagerCallback != NULL)
			updateStreamManagerCallback();

		//wait some milliseconds till next update
		usleep(updateInterval * 1000);
	}
	return NULL;
}



// === WINDOWS THREADS ===
#ifdef _WIN32
	#include <windows.h>

	HANDLE  thread;
	
	int __startThread(){
		thread = CreateThread(0, 0, updateStreamManager, NULL, 0, &threadID);
		return 0;
	};



// === POSIX THREADS ===
// Linux, Mac
#else
	#include <pthread.h>

	pthread_t  thread;
	
	int __startThread(){
		threadID = pthread_create(&thread, NULL, updateStreamManager, NULL);	
		return 0;
	};
#endif
```
This is only used when doing a non-threaded build (so ... in Vanilla BMX).
executing it there leads to a EAV on Windows.

Is there a difference in Windows code to Posix/linux/mac stuff?

When using threads (so default with NG) I use the BRL threads instead:
```BlitzMax
	?threaded
	Global refillBufferMutex:TMutex = CreateMutex()
	Global updateStreamManagerThread:TThread = New TThread
	Global updateStreamManagerThreadEnabled:Int = True
	?

[...]


		?Not threaded
		'print "using external/c stream update threads"
		RegisterUpdateStreamManagerCallback(UpdateStreamManagerCallback)
		StartUpdateStreamManagerThread()
		?threaded
		'print "using internal stream update threads"
		updateStreamManagerThread = CreateThread( UpdateStreamManagerThreadFunction, Null )
		?

[...]

	?threaded
	Function UpdateStreamManagerThreadFunction:Object( data:Object )
		While updateStreamManagerThreadEnabled
			If instance
				LockMutex(refillBufferMutex)
				instance.RefillBuffers()
				UnlockMutex(refillBufferMutex)
			EndIf
			Delay(400) 'waiting time
		Wend

	End Function
	?Not threaded
	Function UpdateStreamManagerCallback:Int()
		If Not instance Then Return False

		instance.RefillBuffers()

		Return True
	End Function
	?
```
Can it stumble somehow over the TMutexes used in the BlitzMax code?
If I did not understand it wrong it does this:
- (wait until it can) lock the mutex
- call the function `RefillBuffers` (which refills buffers of active audio streams)
- unlock the mutex again
- wait 400ms 
- repeat

And as said it works pretty flawless in my tests on linux boxes (and on my Windows notebook). Just the user reported issues - and I was able to replicate it partially in Windows 64bit running in a VM (with 2 vcores).

I dunno (at the moment) why I even decided to use a mutex - it should only be useful if multiple "updateStreamManagerThread" instances would compete for some cpu time.
Maybe it would be enough to measure time before `RefillBuffers()` and only `Delay()` the remaining time so the interval becomes the desired ones.
Or could I fall into a trap somewhere?

------

OK .. meanwhile the user replied and reported that the hickups (and crashes etc) were gone with a new compilate: using rtAudio instead of my sound engine here.
So if that was the reason (for him) I need to find out what is causing the issues.

@HurryStarfish 
If you read this thread and my description sounds a bit "non-saying" then feel free to read the German discussion there:
https://www.gamezworld.de/phpforum/viewtopic.php?id=13853&p=9
(between me (Ronny) and "dirkw").

**Comment by GWRon** [comment]
I replaced my "thread"-code with this:
```BlitzMax
	?threaded
	Function UpdateStreamManagerThreadFunction:Object( data:Object )
		While updateStreamManagerThreadEnabled
			local t:Long = Time.MillisecsLong()
			If instance
				LockMutex(refillBufferMutex)
				instance.RefillBuffers()
				UnlockMutex(refillBufferMutex)
			EndIf
			'wait until 400ms are gone in total
			local d:Int = Max(0, 400 - (Time.MillisecsLong() - t))
			print "delaying: " + d
			Delay(d) 'waiting time
		Wend

	End Function
```
And it delayes for 397-399 ms, means the `RefillBuffers()` code is executed fast enough (~2ms).
Now we should not forget about the fact that it... is running in an extra thread so it should not affect the main thread.

So if the whole `RefillBuffers()` thing was borked up (not refilling fast enough) then this explains "cracks" in the playback or so - but it does NOT explain why the game itself has hickups then (during mouse movement).
This would only be possible with the GC having to do overtime.

**Comment by woollybah** [comment]
What's that 400ms delay for? It does seem rather... specific.

What's the mutex protecting? Do you have multiple stream managers using the same "instance"?

Another option, rather than doing some timing maths, would be to use a semaphore. A semaphore waits (or blocks) until something releases it. If you wanted to refill your buffer as soon as it was emptied, you might do something like this :

Your thread
```blitzmax
Function UpdateStreamManagerThreadFunction:Object( data:Object )
	While updateStreamManagerThreadEnabled
		WaitSemaphore(_semaphore)
		If instance
			instance.RefillBuffers()
		EndIf
	Wend
End Function
```

elsewhere
```blitzmax
Function ConsumeBuffer()
	'
	' cosume the buffer
	'
	If bufferIsEmpty
		' we need more
		PostSemaphore(_semaphore)
	End If
End Function
```
You'd create the semaphore with a count of 1.

This way there's no delay in getting the buffer refilled as it should occur as soon as it has been emptied, and your thread just hangs around waiting to be woken up.

**Comment by woollybah** [comment]
I assume you are not calling back into BlitzMax code in your C example? `updateStreamManagerCallback`
Otherwise you'll need to be very careful - like don't try stepping through in the debugger :-p

**Comment by woollybah** [comment]
If RefillBuffers is retrieving data from a slow device (rather than from some memory cache), you might also consider prefetching the next block of data for the buffer in advance of the buffer being emptied. This would give you some more time to have the data ready before it's required.

**Comment by GWRon** [comment]
The "RefillBuffer" loads ... enough data (115k sample points or how we call it).
The 400ms was just an arbitrary value, could be 600 or 750 too. When it is called it refills "what fits".

I would avoid using a Semaphore and only refilling the buffer once a threshold (or even "buffer empty") is reached. The buffer is what is actually played, so "buffer" is maybe not the right word.

The "buffer" is the memory of an eg. 1 second long audio/sample object. depending on the position of the current playback we can fill in the audio "behind" or "in front". That way the whole audio object can be "looped" but instead of listening to the very same sound we fill in new stuff.

The whole threaded thing is just there to automate the whole process of buffer refilling without requiring the "user" (developer) to call a `sound(manager).update()` on a regular base. This means if you load resources which takes eg. 5 seconds this blocks the main thread - refilling the buffer in another thread allows to playback sound meanwhile.

So the threads just call a method which you would else have to run manually. The C-code does the same thing: you register a callback which the "C-Thread" is executing on a given interval. The Callback is a BlitzMax-function which does then call the `Update()` thing for you.

**Comment by GWRon** [comment]
So if one was to write a "streamed audio sample" support for FreeAudio (so you can do `LoadSound(file, looped, streamed)`) then they would have to use threads too - and may benefit from the experience we made here with this little testbed.

**Comment by GWRon** [comment]
While I understand that my threading-code can be improved in various places there is a question open: why does this code lead to "stuttering mouse movement" on the user's machine? (As said it was gone once I replaced the "FreeAudio+MyStreamingCode" with "rtAudio").
Might FreeAudio already lead to this stuttering? At least it does some software-mixing and other stuff in the main thread. Maybe it is the ASIO/DSound interfaces leading to trouble?

The user's computer is a 2009 i5-750 - so it's 4 cores should be good enough for OS + my 2D game.

**Comment by GWRon** [comment]
Closing this now as I am not using FreeAudio in favor of Soloud.
Also there seems to be no new knowledge added in the foreseeable future.
