### ISSUE TITLE
Win32 Application Settings

### ISSUE THREAD

**Issue by jsp-at-work** [bmx-ng/bmx-ng#86]
I have used the built in application settings instead of a resource file but the "File Version" always stays on 1.0.0.0

I copied from the doc:
app.version.code=1
app.version.name=1.0.0
app.name=BlitzMax Application
app.comments=Comments
app.company=My company
app.description=App description
app.copyright=Copyright text
app.trademarks=All rights reserved

and filled in my own stuff.
When altering app.version.name then the product version number changes, which is ok.
When altering app.version.code I suppose it will change the file version number.

Nevertheless, does not matter what I use at that place, the file version is fixed to 1.0.0.0
As the file version is the version which is shown on hovering the app that one is more important than the product version which is shown correctly using properties.

Is this a bug or am I mistaken that it will change the file version number?
Is it possible somehow to access those settings from inside the application?
Rgds,
-jsp-

**Comment by woollybah** [comment]
Apparently, one must set the `FILEVERSION` value of the `VERSIONINFO` resource. So I've no idea what the `FileVersion` of the `StringFileInfo` block is for then...

The latest version of bmk will now attempt to use the `app.version.name` value to populate `FILEVERSION`.
`FILEVERSION` expects integers for major, minor and patch values. Bmk will attempt to validate the values before using them - an invalid value will output as a zero value.

**Comment by jsp-at-work** [comment]
Thank you!

Here is an example as I use the resources till now:

1 24 "ResourceCreator.manifest"
101 ICON "icon.ico"

1 VERSIONINFO 
FILEVERSION 2,5,4,161
PRODUCTVERSION 2,0,0,0
FILEOS 0x40004
FILETYPE 0x1
{ 
BLOCK "StringFileInfo" 
{ 
 BLOCK "040904b0" 
 { 
  VALUE "Comments", "Not sure where this is displayed?"
  VALUE "CompanyName", "Company shown on hover" 
  VALUE "FileVersion", "2.5.4.161" 
  VALUE "FileDescription", "Displays Info on hover" 
  VALUE "InternalName", "" 
  VALUE "LegalCopyright", "shown in properties" 
  VALUE "LegalTrademarks", "" 
  VALUE "OriginalFilename", "" 
  VALUE "ProductName", "shown in properties" 
  VALUE "ProductVersion", "2,0,0,0" 
 } 
}
BLOCK "VarFileInfo"
{
  VALUE "Translation", 0x0409, 0
}
}

**Comment by woollybah** [comment]
Thanks. I just added support for the fourth level of version number too.

**Comment by jsp-at-work** [comment]
Great. Actually I use the "build-number" myself more than all the major/minor values for the end user.
Thanks.
