### ISSUE TITLE
LoadImageFont only accepts strings

### ISSUE THREAD

**Issue by Vectrex3000** [bmx-ng/bmx-ng#87]
Hi.

LoadImageFont only accepts strings, which means in order to load a font, it's corresponding file must be located in a "directory".  For example "Project Root\Assets\Fonts\MyFont.ttf"

Would you consider changing LoadImageFont so that it can not only load from a path but also from a bank like LoadImage?   I would like to store all of my fonts inside my custom binary, as this is how i store my graphics and audio.  I'm curious as to why LoadImageFont does not support returned banks.

Thank you.

**Comment by GWRon** [comment]
```BlitzMax
Function LoadImageFont:TImageFont( url:Object,size,style=SMOOTHFONT )
```
Seems it allows to pass "objects" (streams, urls,...).

Yet the underlaying freetypefont.mod (which is what you use in the end then only supports file names or "::" (incbin streams?). At least the used function `LoadByteArray()` handles the passed "url" as something it can wrap a stream around.


```BlitzMax
	
	Function Load:TFreeTypeFont( src$,size:Int,style:Int )

		Global ft_lib:Byte Ptr
		
		If Not ft_lib
			If FT_Init_FreeType( Varptr ft_lib ) Return Null
		EndIf

		Local buf:Byte Ptr,buf_size:Int
				
		Local ft_face:Byte Ptr

		If src.Find( "::" )>0
			Local tmp:Byte[]=LoadByteArray( src )
			buf_size=tmp.length
			If Not buf_size Return Null
			buf=MemAlloc( Size_T(buf_size) )
			MemCopy buf,tmp,Size_T(buf_size)
			If FT_New_Memory_Face( ft_lib,buf,buf_size,0,Varptr ft_face )
				MemFree buf
				Return Null
			EndIf
		Else
			If FT_New_Face( ft_lib,src$,0,Varptr ft_face ) Return Null
		EndIf
		
		While size
			If Not FT_Set_Pixel_Sizes( ft_face,0,size ) Exit
			size:-1
		Wend
		If Not size 
			FT_Done_Face ft_face
			Return Null
		EndIf
		
		'Local face:FTFace=New FTFace
		'MemCopy face,ft_face,SizeOf face
		
		Local ft_size:Byte Ptr = bmx_freetype_Face_size(ft_face)
		'Local metrics:FTMetrics=New FTMetrics
		'MemCopy metrics,face.metrics,SizeOf metrics
		
		Local font:TFreeTypeFont=New TFreeTypeFont
		'font._face=face
		font._ft_face=ft_face
		font._style=style
		font._height=bmx_freetype_Size_height(ft_size) Sar 6
		font._ascend=bmx_freetype_Size_ascend(ft_size) Sar 6
		font._descend=bmx_freetype_Size_descend(ft_size) Sar 6
		font._glyphs=New TFreeTypeGlyph[bmx_freetype_Face_numglyphs(ft_face)]
		font._buf=buf
		font._buf_size=buf_size
		
		Return font
	
	End Function
```

**Comment by GWRon** [comment]
The `FreetypeFontLoader` and the `Function Load()` of `TFreeTypeFont` are only letting through strings.

One could change it to ":object" and check for a valid given `TStream(src)` - and then load the data similar to stream.mod's `LoadByteArray()`:

```BlitzMax
Function LoadByteArray:Byte[]( url:Object )
	Local stream:TStream=ReadStream( url )
	If Not stream Throw New TStreamReadException
	Local data:Byte[1024],size:Int
	While Not stream.Eof()
		If size=data.length data=data[..size*3/2]
		size:+stream.Read( (Byte Ptr data)+size,data.length-size )
	Wend
	stream.Close
	Return data[..size]
End Function
```

Within the Freetypefont-mod we could safely use `TStream` as it does not add a new dependency (already used - while TBank isn't).

**Comment by GWRon** [comment]
Ok, got it working but am not sure if Brucey accepts this.

**Comment by GWRon** [comment]
Sample after adjusting the module as done in my pull request:
```BlitzMax
SuperStrict
Framework Brl.GLMax2D
Import Brl.Bank
Import Brl.Freetypefont

Graphics 800,600



Local fontBank:TBank = LoadBank("/usr/share/fonts/truetype/freefont/FreeSans.ttf")
'fails
'Local font:TImageFont = LoadImageFont(fontBank, 12)

'works
Local fontBankStream:TStream = CreateBankStream(fontBank)
Local font:TImageFont = LoadImageFont(fontBankStream, 12)

SetImageFont(font)


Repeat
	Cls
	DrawText("fontBank.size() = " + fontBank.size(), 0, 0)
	Flip
Until KeyHit(KEY_ESCAPE) Or AppTerminate()
```

Remember this only adds support for any `TStream` but not `TBank` (as the TBank can be wrapped in a `TBankStream` and it would add a new dependency). To load from a bank you just need to utilize the `TBankStream` type to be able to pass it too.

_Should_ not be a biggy to add support for a TBank too (if really desired) as it is also just a matter of copying the buffer of the bank to the fonts buffer. But it would of course add a dependency to this module (`import brl.bank`)

```BlitzMax
	Function Load:TFreeTypeFont( src:object,size:Int,style:Int )
[...]
		ElseIf TBank(src)
			Local bank:TBank = TBank(src)
			bank.Lock()
			buf_size = int( bank.Capacity() )
			If Not buf_size Return Null
			'copy bank content into the fonts buffer
			buf=MemAlloc( bank.Capacity() )
			MemCopy(buf, bank.Buf(), bank.Capacity() )
			If FT_New_Memory_Face( ft_lib,buf,buf_size,0,Varptr ft_face )
				bank.Unlock()
				Return Null
			EndIf
		
		ElseIf String(src).Find( "::" )>0
[...]
	End Function
```

**Comment by Vectrex3000** [comment]
What exactly is "override"?   Reports to be undefined, which prevents building.

**Comment by GWRon** [comment]
It is a language feature in bcc-ng for some many months now.

Update your blitzmax ng installation to one of the current releases.


Aside of that: my changes do not use `override`.

**Comment by Vectrex3000** [comment]
> It is a language feature in bcc-ng for some many months now. Update your blitzmax ng installation to one of the current releases. Aside of that: my changes do not use `override`.

I use the latest 0.105 Winx86.

**Comment by GWRon** [comment]
So where are you using it? Which line is "highlighted"?

**Comment by GWRon** [comment]
In your syntaxbomb-thread you just told that "incbin::fontfile.ttf" does fail for now too. Maybe the code used is outdated. Maybe "incbin::" changed a bit between NG and vanilla.

**Comment by Vectrex3000** [comment]
Hi Ron, yes.   INCBIN fails for me, with fonts. -  I rarely use INCBIN, so i was going to use it as a temporarily solution until i could get fonts from by binary (returned as bank).

Crashes without an error thrown.

> Where are you using it?  Which line is highlighted?

I just pasted your edits over the original function in the module.   I guess it was a maxIDE bug because it would throw a fit on "override", but the latest commit for whatever reason works just fine.   It might've been a freak thing.  I'm testing now.

**Comment by woollybah** [comment]
incbin hasn't changed.
You need BRL.RamStream for it to work with the streams stuff though.

**Comment by Vectrex3000** [comment]
For my testing purposes, i'm not using a specific framework.   So, i assume everything is being included already, including ramstream.

**Comment by GWRon** [comment]
My sample even did not need to import brl.bankstream while it should.
Frameworks are efficient but dangerous ...especially with that factory-stuff (code works with base type but eg. support for your file type was forgotten to get imported).


Will try incbin stuff when at work and having a break.

Am 14. Juni 2019 08:25:06 MESZ schrieb Brucey <notifications@github.com>:

**Comment by GWRon** [comment]
Hmm, I tried to check the incbin code (and replace the custom functions with `Incbinlen()` and `Incbinptr()` (of course "incbin::" stripped from name) but then I found out that I cannot display custom fonts at all on this windows box with the current NG code and the above example (even without framework command).

It loads the fonts, populates the glyph array - but output is pure black no matter what color I set. Also tried different fonts - only the inbuilt "system font" is showing something.

**Comment by GWRon** [comment]
Regarding Incbin: it works as soon as you do not forget to "Import Brl.RamStream" (just tried it).

You could skip that if you replaced the code handling the incbin-stuff with this:
```BlitzMax
		'handle "incbin::"-data
		ElseIf String(src).Find( "::" )>0
Rem
				Local tmp:Byte[]=LoadByteArray( src )
				buf_size=tmp.length
				If Not buf_size Return Null
				buf=MemAlloc( Size_T(buf_size) )
				MemCopy buf,tmp,Size_T(buf_size)
				If FT_New_Memory_Face( ft_lib,buf,buf_size,0,Varptr ft_face )
					MemFree buf
					Return Null
				EndIf

EndRem
			Local incbinName:String = String(src)[String(src).Find( "::") + 2 ..]
			buf_size=IncbinLen( incbinName )

			If Not buf_size Return Null
			buf=MemAlloc( Size_T(buf_size) )
			MemCopy buf,IncbinPtr( incbinName ),Size_T(buf_size)
			If FT_New_Memory_Face( ft_lib,buf,buf_size,0,Varptr ft_face )
				MemFree buf
				Return Null
			EndIf
```

**Comment by GWRon** [comment]
@Vectrex3000 
Brucey just upped a new freetypefont.mod update adding "TBank" support (so no need to wrap it in a `TBankStream` anymore).

Give it a whirl and report back.

Nonetheless we should have a look into the issue you have with the bankstreams and Brucey's variant of the above patch.

**Comment by Vectrex3000** [comment]
> @Vectrex3000
> Brucey just upped a new freetypefont.mod update adding "TBank" support (so no need to wrap it in a `TBankStream` anymore).
> 
> Give it a whirl and report back. It _might_ fail the same as it fails for you with the TStream, as both functions in essence do the same then: passing an array of bytes to the FreeType-function creating the font face out of a memory blob.
> 
> Especially if it works we should have a look into the issue you have with the bankstreams and Brucey's variant of the above patch.


Something is simply borked.    I cannot get a TBANK to load whatsoever.

The only way i am able to load a font is by manual saying "Data\Arial.ttf".

I can't loadbank("Data\Arial.ttf")  (which is the exact same thing) and i can't pull it from my archive;  the default font is always pulled.

I saved the output; Files are IDENTICAL, so there isn't an issue there.  I'm quite baffled why it only wants to accept literal strings.  I'm not sure what to say anymore.

**Comment by GWRon** [comment]
Did you do a complete update or did you just copy paste the load-function?

Asking as there is another change at the bottom of the file (which previously limited to "string" only).

**Comment by Vectrex3000** [comment]
> Did you do a complete update or did you just copy paste the load-function? Asking as there is another change at the bottom of the file (which previously limited to "string" only).

Hi, you are right, there was a change to the bottom of the module, which i had overlooked.  I'm sorry about this mishap.

Good news, works!   I was successfully able to load multiple fonts, via TBANK, from my archive!
