### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by wombatswaffles** [bmx-ng/bmx-ng#88]
BlitzMax doesn't seem to allow the use of Enum anymore, so [things like this](https://www.syntaxbomb.com/index.php?topic=4391.0) don't work anymore. Is that intentional?

**Comment by HurryStarfish** [comment]
Yes, it is intentional. BlitzMax-NG now has language support for [Enum (enumeration) types](https://blitzmax.org/docs/en/language/enums/).
Thus, `Enum` has been added as a keyword.

**Comment by wombatswaffles** [comment]
Ah, cool. Thanks for replying.
